### ISSUE TITLE
android/8BitDo SN30 Pro+ (Switch Mode).cfg: unexpected "Device config name: Pro Controller.cfg" in System Information

### ISSUE THREAD

**Issue by davidhedlund** [libretro/retroarch-joypad-autoconfig#1064]
Tested on Android 10.

# 8BitDo SN30 Pro+ (Switch Mode) (Issue)

* The only autoconfig file that contains the text "Switch Mode" is [android/8BitDo SN30 Pro+ (Switch Mode).cfg](https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/android/8BitDo%20SN30%20Pro%2B%20(Switch%20Mode).cfg)

```
input_driver = "android"
input_device = "Pro Controller"
input_device_display_name = "8BitDo SN30 Pro+ (Switch Mode)"
input_vendor_id = "1406"
input_product_id = "8201"
```

* [hid/Pro Controller.cfg](https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/hid/Pro%20Controller.cfg) does not contain "8BitDo SN30 Pro+ (Switch Mode)"

```
input_driver = "hid"
input_device = "Pro Controller"
input_vendor_id = "1406"
input_product_id = "8201"
```

![image](https://github.com/libretro/retroarch-joypad-autoconfig/assets/6416073/2e125135-21da-4258-89bb-8b0effdaf364)

![image](https://github.com/libretro/retroarch-joypad-autoconfig/assets/6416073/c6266c96-c179-4d5d-9dc3-24e36514fb27)

## DualSense (control)
Everything is displayed as expected, [android/Sony_DualSense.cfg](https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/android/Sony_DualSense.cfg)

```
input_driver = "android"
input_device = "Wireless Controller"
input_device_display_name = "DualSense"
input_vendor_id = "1356"
input_product_id = "3302"
```

![image](https://github.com/libretro/retroarch-joypad-autoconfig/assets/6416073/be6bcdad-4daa-41a6-89cf-dc52169a5697)

Same driver information:

![image](https://github.com/libretro/retroarch-joypad-autoconfig/assets/6416073/c6266c96-c179-4d5d-9dc3-24e36514fb27)

**Comment by davidhedlund** [comment]
* https://github.com/libretro/retroarch-joypad-autoconfig/issues/946

**Comment by RobLoach** [comment]
Perhaps try d-input mode for this one?

**Comment by davidhedlund** [comment]
> Perhaps try d-input mode for this one?

The controller is "working"[1]. The reason why I opened this issue is that I want to understand if [hid/Pro Controller.cfg](https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/hid/Pro%20Controller.cfg) is loaded, and if android/8BitDo SN30 Pro+ (Switch Mode).cfg is loaded later (input_device_display_name = "8BitDo SN30 Pro+ (Switch Mode)")

1: The Bluetooth issue for Nintendo Switch Pro Controller in Android 11 or lower makes is useless for gaming.

**Comment by davidhedlund** [comment]
Solved:
* https://github.com/libretro/retroarch-joypad-autoconfig/pull/1106
