### ISSUE TITLE
Proposed new joypad archive

### ISSUE THREAD

**Issue by davidhedlund** [libretro/retroarch-joypad-autoconfig#1069]
I suggest that we open an archive for data and photos of gamepad controllers that we can use as reference for our autoconfig files. I've taken some photos of my Sony DualSense controller

# Sony DualSense 2nd generation
![IMG_20231212_011747](https://github.com/libretro/retroarch-joypad-autoconfig/assets/6416073/c9618dc9-94cb-4d7c-b412-34e47fbc7a95)

## Backside text
WIRELESS CONTROLLER MODEL CFI-ZCT1W A 5V=1500mA MADE IN CHINA
TPBY  UKCA  EAC  CE
Sony Interactive Enertainment Inc. 1-7-1 Konan Minato-ku Tokyo, 108-0075 Japan
ANTEL: 08316-20-06223 IC: 409B-CFIZCT1A CONATEL PY: 2021-04-1-0193 F22200VYP27302935
Verified  IFT No: RCPSOCF20-1880
FCC ID: AK8CFIZCT1A  CNC ID: C-25206
UL Energy NOM
SONY

OCR reference photo of the backside of the controller:

![image](https://github.com/libretro/retroarch-joypad-autoconfig/assets/6416073/6b800d9d-2f65-4a1b-b496-4c2dcb2667e6)

Note: The QR code generates the serial number (in my case F22200VYP27302935) written further down on the controller (source: https://www.playstation.com/en-us/support/hardware/find-dualsense-controller-serial-number/).

# Notes
Superficial indications that verified that I got a second generation controller:
* "CFI-ZCT1W A" (note the extra " A") is said to be the second generation model
* The photo of the pressed L2 button (see below)

Sources:
* https://youtu.be/ZNtMN8HKn2c
* https://www.consoleskins.nl/en/manuals/what-generation-controller-do-i-have/playstation-5/

## Photos
![IMG_20231212_012813](https://github.com/libretro/retroarch-joypad-autoconfig/assets/6416073/601f32e7-c92f-4ff4-9343-c9293146e1de)
![IMG_20231212_011918](https://github.com/libretro/retroarch-joypad-autoconfig/assets/6416073/7f15fb27-593f-4e56-94c3-2ae31041a54b)
![IMG_20231212_012638](https://github.com/libretro/retroarch-joypad-autoconfig/assets/6416073/b591a52f-ea57-4f38-b0cc-5455978168b9)
![IMG_20231212_012322](https://github.com/libretro/retroarch-joypad-autoconfig/assets/6416073/35ac874e-8b78-4a18-a476-212cd676fc13)
![IMG_20231212_013123](https://github.com/libretro/retroarch-joypad-autoconfig/assets/6416073/e4c5a6bc-8d23-4216-a41a-0288932eaa58)
![IMG_20231212_013113](https://github.com/libretro/retroarch-joypad-autoconfig/assets/6416073/6ddd06b6-4d87-4aa7-93ab-0e37e856713d)
![IMG_20231212_012712](https://github.com/libretro/retroarch-joypad-autoconfig/assets/6416073/e49b8d61-baee-4764-aa3c-c8713bdf3c7b)

**Comment by geogolem** [comment]
I was thinking along with default button mappings etc. it might be useful to include corresponding helper Icons for the various controllers... I mean retroarch doesn't do it right now.. but with how well SDL seems to be able to detect various controllers, it could be a potential addition to improve the button mapping to actual use help icons corresponding to the controllers.

**Comment by davidhedlund** [comment]
> I was thinking along with default button mappings etc. it might be useful to include corresponding helper Icons for the various controllers... I mean retroarch doesn't do it right now.. but with how well SDL seems to be able to detect various controllers, it could be a potential addition to improve the button mapping to actual use help icons corresponding to the controllers.

Thank you for your feedback.

What are helper Icons specifically?

Can you please upload an image?

**Comment by geogolem** [comment]
> > I was thinking along with default button mappings etc. it might be useful to include corresponding helper Icons for the various controllers... I mean retroarch doesn't do it right now.. but with how well SDL seems to be able to detect various controllers, it could be a potential addition to improve the button mapping to actual use help icons corresponding to the controllers.
> 
> Thank you for your feedback.
> 
> What are helper Icons specifically?
> 
> Can you please upload an image?

like the buttons contained here; https://www.reddit.com/r/gamedev/comments/1z0zid/free_keyboard_and_controllers_prompts_pack/

or the ones here: https://www.ssbwiki.com/Category:Button_icons_(N64)

**Comment by davidhedlund** [comment]
> > > I was thinking along with default button mappings etc. it might be useful to include corresponding helper Icons for the various controllers... I mean retroarch doesn't do it right now.. but with how well SDL seems to be able to detect various controllers, it could be a potential addition to improve the button mapping to actual use help icons corresponding to the controllers.
> > 
> > 
> > Thank you for your feedback.
> > What are helper Icons specifically?
> > Can you please upload an image?
> 
> like the buttons contained here; https://www.reddit.com/r/gamedev/comments/1z0zid/free_keyboard_and_controllers_prompts_pack/
> 
> or the ones here: https://www.ssbwiki.com/Category:Button_icons_(N64)

Thank you.

**Comment by geogolem** [comment]
> > > > I was thinking along with default button mappings etc. it might be useful to include corresponding helper Icons for the various controllers... I mean retroarch doesn't do it right now.. but with how well SDL seems to be able to detect various controllers, it could be a potential addition to improve the button mapping to actual use help icons corresponding to the controllers.
> > > 
> > > 
> > > Thank you for your feedback.
> > > What are helper Icons specifically?
> > > Can you please upload an image?
> > 
> > 
> > like the buttons contained here; https://www.reddit.com/r/gamedev/comments/1z0zid/free_keyboard_and_controllers_prompts_pack/
> > or the ones here: https://www.ssbwiki.com/Category:Button_icons_(N64)
> 
> Thank you.

Just wanted to note this interesting project, which seems relevant: https://github.com/rsubtil/controller_icons

**Comment by davidhedlund** [comment]
> > > > > I was thinking along with default button mappings etc. it might be useful to include corresponding helper Icons for the various controllers... I mean retroarch doesn't do it right now.. but with how well SDL seems to be able to detect various controllers, it could be a potential addition to improve the button mapping to actual use help icons corresponding to the controllers.
> > > > 
> > > > 
> > > > Thank you for your feedback.
> > > > What are helper Icons specifically?
> > > > Can you please upload an image?
> > > 
> > > 
> > > like the buttons contained here; https://www.reddit.com/r/gamedev/comments/1z0zid/free_keyboard_and_controllers_prompts_pack/
> > > or the ones here: https://www.ssbwiki.com/Category:Button_icons_(N64)
> > 
> > 
> > Thank you.
> 
> Just wanted to note this interesting project, which seems relevant (although it uses SDL3): https://github.com/icculus/ControllerImage

Please submit a feature request to https://github.com/libretro/RetroArch/issues?q=is%3Aissue+is%3Aopen+SDL3 which you may want to include these links in:
* https://github.com/libsdl-org/SDL/milestone/10
* https://discourse.libsdl.org/t/how-soon-will-the-first-stable-version-of-sdl3-be-released/46024/3

**Comment by RobLoach** [comment]
Feel free to make your own repo and start up the archive yourself :wink:
