### ISSUE TITLE
Suggestion: Begin cfg files with "Company - " or "Company "

### ISSUE THREAD

**Issue by davidhedlund** [libretro/retroarch-joypad-autoconfig#1089]
For starters, I just created a [PR](https://github.com/libretro/retroarch-joypad-autoconfig/pull/1068/files): $lsusb says: "Sony Corp. DualSense Wireless Controller" -- so should I rename the file to "Sony Corp. DualSense Wireless Controller.cfg". Personally, I strongly prefer just Sony_DualSense.cfg since it's short and concise.

I proposed PRs with "Sony ", and "Nintendo " in the beginning of filenames for controllers made by these companies. I need it to organize, so I can proceed with more detailed working plans. Furthermore, I own both a Sony DualSense (PS5), and a Nintendo Switch Pro Controller, and I've contributed to these controllers.

# Company name is used in Retroarch: Online Updater -> Core Downloader
For the sake of consistency, it would be useful if we followed RetroArch core title naming standard for the autoconfig files, in my opinion.

Example in Retroarch: Online Updater -> Core Downloader:
* Nintendo - SNES / SFC (bsnes)

# Company name is generally preferred for normal screen size

Example for DualSense:
* In GNU/Linux, $lsusb: `Sony Corp. DualSense Wireless Controller`
* In Android, the Bluetooth device name is: `DualSense Wireless Controller`

Example for Nintendo Switch Pro Controller:
* In GNU/Linux, $lsusb: `Nintendo Co., Ltd Switch Pro Controller`
* In Android, the Bluetooth device name is: `Pro Controller`

So to group the files alphabetically, they must start with the company name.

**Comment by RobLoach** [comment]
It all depends on the `input_device` name that's reported from the input driver. That way if someone wants to re-save the autoconfig, it'll overwrite the original file.

**Comment by davidhedlund** [comment]
> It all depends on the `input_device` name that's reported from the input driver. That way if someone wants to re-save the autoconfig, it'll overwrite the original file.

A new script that I've been working on for a few days, will make sure that the `input_device` is always correct from now on.

**Comment by davidhedlund** [comment]
> > It all depends on the `input_device` name that's reported from the input driver. That way if someone wants to re-save the autoconfig, it'll overwrite the original file.
> 
> A new script, that I've been working on for a few days, will make sure that the `input_device` is always correct from now on.

My script that I've spent about 24 hours on is useless: TODAY I discovered that `Settings -> Input -> RetroPad Binds -> Port 1 Controls -> Save Controller Profile` will generate a .cfg file in the autoconfig directory. It will generate a proper `input_device` variable in any OS (including Android).

I was sure that `Save Controller Profile` stored it in retroarch.cfg, so I used to run `grep "player1_" ~/.config/retroarch/retroarch.cfg | grep "_btn" && grep input_menu_toggle_btn ~/.config/retroarch/retroarch.cfg`. My script did much more than that, but it's not needed since RA can do all of that. 🤦

# Issues
* The [documentation](input_device) does not mention that the generated file will be saved in the `autoconfig` directory.
* When you run `Settings -> Input -> RetroPad Binds -> Port 1 Controls -> Save Controller Profile` it says "Controller profile saved successfully.", but it should clearly say[1] "Saved new controller profile to [controller profile directory]/[$input_device].cfg.", for example  "Saved new controller profile to /home/gamerjoe/Downloads/[$input_device].cfg." so people don't assume that it was saved in retroarch.cfg.

1: Main Menu -> Configuration File -> Save Current Configuration -- says "Saved new config to .../retroarch.cfg"

I'll open a new [RetroArch](https://github.com/libretro/RetroArch) issue for this.

**Comment by davidhedlund** [comment]
* https://github.com/libretro/RetroArch/issues/16121
