### ISSUE TITLE
Revert a file name change

### ISSUE THREAD

**Issue by davidhedlund** [libretro/retroarch-joypad-autoconfig#1097]
Today I learned how RA is generating the .cfg files, an issue that I filed prevented me from understanding this earlier:
* https://github.com/libretro/RetroArch/issues/16121

With that said. One of my old PR went through with file names changes should be reverted in order to make sure that the controller name in the file name matches `input_device`:
* https://github.com/libretro/retroarch-joypad-autoconfig/pull/1056

**Comment by RobLoach** [comment]
That's a comment at the top of the file. Doesn't really matter.
