### ISSUE TITLE
Nintendo Switch Pro Controller Regression

### ISSUE THREAD

**Issue by Lustyn** [libretro/retroarch-joypad-autoconfig#1145]
The latest version of autoconfig causes Nintendo Switch Pro controllers to be misidentified as "Retro Fighter Brawler64 Wireless Gamepad".

This is almost definitely caused by #1137, but I'm not 100% sure on why. Likely though its just because they share the exact same vendor and product ID, but I can't verify this as I don't own any Brawler64 controllers. IMO RetroArch shouldn't ship with a config which breaks common controllers so widely.

**Comment by hizzlekizzle** [comment]
Yes, this looks like a simple mistake.

If you go into that "wireless gamepad" profile and comment out (i.e., put a # / hash sign in front of) the product ID but leave the vendor ID, does that allow it to identify your Switch Pro controller again? Or does it need both vid *and* pid commented?

**Comment by Lustyn** [comment]
I can confirm that commenting out the the product ID fixes this.

**Comment by Lustyn** [comment]
I opened a PR (#1146) for what I presume will fix it.
