### ISSUE TITLE
Inconsistent labeling for pressure sensitive buttons on PlayStation controllers for PlayStation 2 or later

### ISSUE THREAD

**Issue by davidhedlund** [libretro/retroarch-joypad-autoconfig#1163]
### Description
The current labels for PlayStation 2 and later controllers do not consistently indicate pressure sensitivity. Specifically, the labels for L2 and R2 buttons do not include the term "Analog," which is used for other pressure-sensitive controls.

Variables with a name ending in `_axis_label` and including "Analog" indicate pressure sensitivity. However, the current labels for L2 and R2 do not follow this convention, even though these buttons are pressure-sensitive on PlayStation 2 and later controllers. Updating these labels will improve consistency and clarity in the codebase.

### Current Labels for controllers for PlayStation 2 and later

```
input_b_btn_label = "Cross"
input_y_btn_label = "Square"
input_select_btn_label = "Create"
input_start_btn_label = "Options"
input_up_btn_label = "D-Pad Up"
input_down_btn_label = "D-Pad Down"
input_left_btn_label = "D-Pad Left"
input_right_btn_label = "D-Pad Right"
input_a_btn_label = "Circle"
input_x_btn_label = "Triangle"
input_l_btn_label = "L1"
input_r_btn_label = "R1"
input_l2_axis_label = "L2"
input_r2_axis_label = "R2"
input_l3_btn_label = "L3"
input_r3_btn_label = "R3"
input_l_x_plus_axis_label = "Left Analog X+ (right)"
input_l_x_minus_axis_label = "Left Analog X- (left)"
input_l_y_plus_axis_label = "Left Analog Y+ (down)"
input_l_y_minus_axis_label = "Left Analog Y- (up)"
input_r_x_plus_axis_label = "Right Analog X+ (right)"
input_r_x_minus_axis_label = "Right Analog X- (left)"
input_r_y_plus_axis_label = "Right Analog Y+ (down)"
input_r_y_minus_axis_label = "Right Analog Y- (up)"
input_menu_toggle_btn_label = "PS"
```

### Current Labels for controllers for PlayStation Classic
The original PlayStation controller does not use analog triggers:

example for [udev](https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/PlayStation_Classic_Controller.cfg):
```
input_l_btn = "6"
input_l2_btn = "4"
```

### Proposed Changes
To maintain consistency and clarity, and to distinguish PS 1 from controllers for PlayStation 2 or later, I propose updating the labels for the L2 and R2 buttons to explicitly indicate their pressure sensitivity by including the term "Analog."

Change:

```
input_l2_axis_label = "L2"
input_r2_axis_label = "R2"
```

To:

```
input_l2_axis_label = "L2 Analog"
input_r2_axis_label = "R2 Analog"
```

This change will make it clear that L2 and R2 buttons are pressure-sensitive, aligning with the labeling convention used for other analog controls.

### Affected projects
 If implemented, the labels should be updated in the following projects: 
* [Done](https://github.com/libretro/docs/pull/969): https://github.com/libretro/docs/blob/master/docs/guides/controller-autoconfiguration.md#sony-playstation-controllers
* Done: Software that generates autoconfig files (for example my Bash script).
* The current autoconfig files (https://github.com/libretro/retroarch-joypad-autoconfig)

**Comment by RobLoach** [comment]
In most places, the controller shows these labels as L2 and R2, without specifically depicting "Analog", so I don't believe this is needed. For example...
![controller_ps2_diagram](https://github.com/user-attachments/assets/af746961-7bc9-4e99-9df5-3a085e3d70ba)

**Comment by davidhedlund** [comment]
> In most places, the controller shows these labels as L2 and R2, without specifically depicting "Analog", so I don't believe this is needed. For example... ![controller_ps2_diagram](https://private-user-images.githubusercontent.com/25086/358153350-af746961-7bc9-4e99-9df5-3a085e3d70ba.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMjg2MjIsIm5iZiI6MTcyNTMyODMyMiwicGF0aCI6Ii8yNTA4Ni8zNTgxNTMzNTAtYWY3NDY5NjEtN2JjOS00ZTk5LTlkZjUtM2EwODVlM2Q3MGJhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDAxNTIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxZmQzMmU3YzNlNzlmYzY3N2IyYjE3M2MwNTNiZTdmZTBhZTc4ZDhhZGU2MGQzMDdhMjAxNGUxZTU0ZTljODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0IBp4-abdnAyUJBBpSTTTaURNzuuNSq5eho_X-l5Nzw)

Some controllers, like the original PlayStation controller and the Nintendo Switch Pro Controller, lack analog L2/R2 buttons. Given the variety of controllers, it is beneficial to differentiate their features.

**Comment by davidhedlund** [comment]
Digital L2/R2 buttons are typically referred to as bumper buttons, whereas analog L2/R2 buttons are commonly known as triggers.

**Comment by davidhedlund** [comment]
I completely understand if you're unable to update these autoconfig files due to time constraints. However, my aim was to create a script that identifies analog L2/R2 and appends "Analog" to their labels. What do you think?

**Comment by davidhedlund** [comment]
> In most places, the controller shows these labels as L2 and R2, without specifically depicting "Analog", so I don't believe this is needed. For example... ![controller_ps2_diagram](https://private-user-images.githubusercontent.com/25086/358153350-af746961-7bc9-4e99-9df5-3a085e3d70ba.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMzgwMTYsIm5iZiI6MTcyNTMzNzcxNiwicGF0aCI6Ii8yNTA4Ni8zNTgxNTMzNTAtYWY3NDY5NjEtN2JjOS00ZTk5LTlkZjUtM2EwODVlM2Q3MGJhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA0MjgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxZDBhYzcxYTFlZDk3YjNhOWM2MzUxYTIxOGY3MzIzZTJiOTNhZGFkMGVjYzI0NTVkYzc3ZTc4Y2MxZTZkNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yUKsBLMq4i3ZqnTokkWbQuRrT95l3MKUejLBt-BZVMQ)

I don't mind if we call them "L1 bumper" / "L1 trigger", and "R1 bumper" / "R1 trigger" instead:

![image](https://github.com/user-attachments/assets/559073d4-4283-4a4f-9ea0-e4e9edd452f8)

My aim was to create a script that identifies analog L2/R2 input variables and appends " Trigger" (or " Analog") to their labels. What do you think?

**Comment by davidhedlund** [comment]
* https://github.com/libretro/docs/pull/986
