### ISSUE TITLE
[Feature request] Downloading and OS-specific archives

### ISSUE THREAD

**Issue by davidhedlund** [libretro/retroarch-joypad-autoconfig#1187]
The command `wget -q https://github.com/libretro/retroarch-joypad-autoconfig/zipball/master/ -O master.zip` downloads all directories, including those not needed by the specific operating system performing the download.

For GNU/Linux, an archive containing only the latest versions of the following directories would be beneficial:
* linuxraw
* parport
* sdl2
* udev

If this feature is activated, we could submit a request for RetroArch to identify and download archives specific to the operating system.

**Comment by hizzlekizzle** [comment]
these files are very small. I don't think the benefits would outweigh the additional maintenance burden.

**Comment by davidhedlund** [comment]
> these files are very small. I don't think the benefits would outweigh the additional maintenance burden.

In free systems like Trisquel GNU/Linux (a Free Sofware Foundation approved distri), it's unusual to encounter directories dedicated to proprietary drivers.

**Comment by davidhedlund** [comment]
https://github.com/hizzlekizzle/RetroArch-AppImage/issues/15

**Comment by davidhedlund** [comment]
> these files are very small. I don't think the benefits would outweigh the additional maintenance burden.

Thank you for your feedback.
