### ISSUE TITLE
Suggestion for file naming scheme and style guidelines

### ISSUE THREAD

**Issue by CaptainAlphabet** [libretro/retroarch-joypad-autoconfig#166]
Hi!

The current situation is that we have different naming schemes like
- **Some Example Gamepad 1.cfg**
- **Some-Example-Gamepad-2.cfg**
- **Some_Example_Gamepad_3.cfg**

inside this repository. For getting consistency my suggestion would be to specify one naming scheme and rename all files. Using space as word delimiter would lead to best legibility. What do you think?

Next we should look at the file content itself. paalfe rearranged the layout of some config files (thank you for your commitment), where he split the blocks for button mapping and labelling into smaller blocks which now look like
- **idenfication** (driver, vid, pid, name, ...)
- **mapping** (a = 96, b = 97, ...)
- **labels** (a = "A", b = "B", ...)
- **mapping** (up = 19, down = 20, ...)
- **labels** (up = "D-Pad Up", down = "D-Pad Down", ...)

In my opinion this is quiet not as comfortable when watching or updating the file as the previous layout which was
- **idenfication** (driver, vid, pid, name, ...)
- **mapping** (a = 96, b = 97, ... up = 19, down = 20, ...)
- **labels** (a = "A", b = "B", ... up = "D-Pad Up", down = "D-Pad Down", ...)

Separating each block by a blank line would increase legibility.

So what's your opinion? Please let's discuss. :-)

**Comment by Kivutar** [comment]
Yes. Having cleaner files and documented conventions is never a bad thing.

**Comment by hizzlekizzle** [comment]
Yeah, some sort of standard is a good idea.

I would prefer to leave spaces out of filenames.

**Comment by Kivutar** [comment]
Yeah, we can't use the display name anyway, since it can contain special characters like slashes.

**Comment by CaptainAlphabet** [comment]
Thank you for your feedback. So the way to go should be

- **Some_Example_Gamepad.cfg**

for filenames and

- **idenfication** (driver, vid, pid, name, ...)
- blank line
- **mapping** (a = 96, b = 97, ... up = 19, down = 20, ...)
- blank line
- **labels** (a = "A", b = "B", ... up = "D-Pad Up", down = "D-Pad Down", ...)

for the content? Any objection?

**Comment by fr500** [comment]
It's pointless to rename unless you make the function that sabes the
profiles use the same convention and it doesn't

**Comment by CaptainAlphabet** [comment]
Well, for evaluation it doesn't matter how the files are named or how they are structured internally as long as the syntax is valid and that is completely fine. But as for programming languages style guidelines help to avoid (or at least reduce) mess.

**Comment by lasers** [comment]
>It's pointless to rename unless you make the function that sabes the
profiles use the same convention and it doesn't

What about hiding? `Steam Controller.cfg` --> `.Steam_Controller.cfg`

If you made a custom config, it would then show up as `Steam Controllers.cfg` in that directory. All autoconfig cfg are to be considered as template cfg. We then can set up some naming convention and not having to worry about constantly matching up with the devicename or figuring out how to deal with ugly filenames. All those odd Sony knockoff controllers can have random filenames, hashes, or something more manageable as long as it stays hidden?

```
.Logitech - Dual Action (LOHHH-J423).cfg
.Sony - DualShock2 (WeirdControllerSSS22).cfg
.Sony - DualShock3 (JEESUS_GamePAD3).cfg
.Sony - DualShock3 (WEEEP_Game_PAD).cfg
.Sony - DualShock4 (FORYOU X4 V3.2).cfg
.Sony - DualShock4 (DualSHOCKV333).cfg
.Microsoft - SideWinder Dual Strike.cfg
```

**Comment by RobLoach** [comment]
I'm unsure that having them as hidden files is a good convention. Keeping them the same as the export makes saving updates directly back up to autoconfig really easy, since you just do a diff.

Some parsing and cleaning up in the .cfg files is always nice. A good example of a config that looks nice is:
https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/3H%20Dual%20Arcade.cfg
