### ISSUE TITLE
Xbox 360 Receiver (1118/1817) not Conifgured

### ISSUE THREAD

**Issue by dmbreton** [libretro/retroarch-joypad-autoconfig#172]
I am getting this error when running a ROM.

"Xbox 360 Receiver (1118/1817) not Conifgured"

I installed using [SteamOS-Tools](https://github.com/ProfessorKaos64/Ice) and no controllers seem to work.  

This is the command being used to execute the retroarch

"/usr/bin/retroarch" -f -L "/usr/lib/libretro/fceumm_libretro.so" "/home/steam/ROMs/NES/Bubble Bobble (U).nes"

I can see the "Xbox_360_Wireless_Receiver.cfg" in "/usr/share/libretro/autoconfig" and the 

```
input_device = "Xbox 360 Wireless Receiver"
input_driver = "udev"
input_vendor_id = 1118
input_product_id = 1817
input_b_btn = "0"
input_y_btn = "2"
input_select_btn = "6"
input_start_btn = "7"
input_up_btn = "13"
input_down_btn = "14"
input_left_btn = "11"
input_right_btn = "12"
input_a_btn = "1"
input_x_btn = "3"
input_l_btn = "4"
input_r_btn = "5"
input_l2_axis = "+2"
input_r2_axis = "+5"
input_l3_btn = "9"
input_r3_btn = "10"
input_l_x_plus_axis = "+0"
input_l_x_minus_axis = "-0"
input_l_y_plus_axis = "+1"
input_l_y_minus_axis = "-1"
input_r_x_plus_axis = "+3"
input_r_x_minus_axis = "-3"
input_r_y_plus_axis = "+4"
input_r_y_minus_axis = "-4"
input_menu_toggle_btn = "8"
...
```

**Comment by hizzlekizzle** [comment]
Looks like ProfessorKaos64 fixed this in his packaging, so I'm closing this issue.
