### ISSUE TITLE
Retrolink SNES conflict

### ISSUE THREAD

**Issue by soccerties** [libretro/retroarch-joypad-autoconfig#176]
I got the Retrolink SNES gamepad on [amazon](http://www.amazon.com/Nintendo-Retrolink-Super-Classic-Controller-NES/dp/B002824SNS/) and was adding the autoconfig profile when I noticed the input_product_id is identical to Retrolink-Sega-Saturn-USB-GamePad.cfg. I think this will cause a problem because the button mappings are different.

Sega
input_b_btn = "1"
input_y_btn = "0"
input_start_btn = "8"
input_up_axis = "-1"
input_down_axis = "+1"
input_left_axis = "-0"
input_right_axis = "+0"
input_a_btn = "2"
input_x_btn = "3"
input_l_btn = "6"
input_r_btn = "7"
input_l2_btn = "4"
input_r2_btn = "5"

SNES
input_b_btn = "2"
input_y_btn = "3"
input_select_btn = "8"
input_start_btn = "9"
input_up_axis = "-1"
input_down_axis = "+1"
input_left_axis = "-0"
input_right_axis = "+0"
input_a_btn = "1"
input_x_btn = "0"
input_l_btn = "4"
input_r_btn = "5"

I noticed this because even after getting the autoconf generated. Whenever I plugged in the controller the button mappings would be wrong. Is this behavior due to the different button mappings?

**Comment by hizzlekizzle** [comment]
Yeah, in that case, the only option is to delete the conflicting one and just keep your own working version. I'm not sure how best to go about handling these sorts of conflicts...

**Comment by fr500** [comment]
Basically, it's the manufacturer's fault, there isn't another field we can use to differentiate them.

**Comment by hizzlekizzle** [comment]
Yeah, I just mean: should we delete them all to avoid confusion? Keep the first one submitted? Something else?

**Comment by fr500** [comment]
I think keep them, some autoconfigurability is better than no way to autoconf

**Comment by mudlord** [comment]
Retrolink is fucked to hell, it will also conflict with the N64 controller too.
