### ISSUE TITLE
8bitdo NES30 PRO only works arrows with firmware 1.69

### ISSUE THREAD

**Issue by Rodrigomezs** [libretro/retroarch-joypad-autoconfig#186]
Can anyone update cfg for 8bitdo nes30 PRO with the newer firmware?
I am trying to connect by bluetooth, it conects and recognize the device as NES 30 PRO Joystick but only works arrows, joystick and start button, A B X and Y dont works.

How can i update this?

**Comment by Kivutar** [comment]
We should ask @paalfe maybe?

**Comment by paalfe** [comment]
I'll take a look at the new 8bitdo firmware(s), update my controllers and see whats new...

**Comment by Rodrigomezs** [comment]
thanks guys!

**Comment by paalfe** [comment]
Pull request for updated configs for udev created - #188 . 

Next is Android...

**Comment by paalfe** [comment]
Pull request for updated configs for android created - #191 .

Issue solved.

**Comment by Kivutar** [comment]
Not sure if it is related, but on Linux with udev, with my 8bitdo zero, I just get the directionnal arrows. I checked with jstest. And I do have the udev rules.

**Comment by paalfe** [comment]
what do "tail -f /var/log/syslog" show when you connect/disconnect it?

**Comment by Rodrigomezs** [comment]
offtopic: 
> How do I update the autoconfig files now that is hiden in updates lakka menu? Should I use SSH?

Thanks

**Comment by Kivutar** [comment]
@Rodrigomezs you wait a few days and use Lakka Update

**Comment by paalfe** [comment]
I have two zero gamepads, one blue colored (bought when it was introduced) and one famicom edition (red colored). They both is identified as "8Bitdo Zero GamePad" with Decimal vid:pid = 1440:12850, but they have different mappings. There is no firmware releases available and I'm not sure if there is different mappings of the blue colored gamepad or if the difference is only blue colored vs. famicom edition.

**Comment by paalfe** [comment]
Pull request #195

**Comment by fr500** [comment]
I was thinking we should make it possible to load a profile manually... 
It kinda defeats the purpose of autoconf but some manufacturers pull shit like this causing all kinds of problems (like mayflash using the same PID/VID for several different devices)

**Comment by RobLoach** [comment]
There have been many updates to 8bitdo configs. Feel free to make a new issue if this is still an issue.
