### ISSUE TITLE
Add menu controls to autoconfig profiles

### ISSUE THREAD

**Issue by tony971** [libretro/retroarch-joypad-autoconfig#207]
I would like the ability to configure settings like menu_ok_btn and menu_cancel_btn on a per-controller basis. Controllers designed for nintendo systems use one standard. Xbox/playstation controllers use another. The ability to use both simultaneously isn't currently possible.

**Comment by twinaphex** [comment]
I don't really like to promote any divergencies here. We follow the RetroPad standard here, which is the Nintendo-based button convention. Having different OK/cancel buttons per autoconfig would just result in a huge nonstandard mess.

**Comment by tony971** [comment]
The autoconfigs don't need to include these settings by default. I'd just like to be able to set them manually and use a "nul" setting in the retroarch.cfg

**Comment by tony971** [comment]
Isn't that the purpose for those settings in the first place?

**Comment by twinaphex** [comment]
The autoconfig profiles is to map RetroPad button defaults to the joypad.

**Comment by twinaphex** [comment]
I'm not sure to be honest and I think it's too late in the game to start adding settings for such buttons with all the pre-existing configs out anyways.

**Comment by tony971** [comment]
It's not something that needs set in each autoconfig. 99% of the time, it should be a non-listed setting, set to "nul." But for people like me, who like to use the button conventions of the controller, I'd like to be able to set them manually by adding the lines.

**Comment by AlexB3D** [comment]
I agree with tony971. It is uncomfortable assign letter (A)> (B) in retropad> (A) Control Xbox. I know it's a lot of work, but I make two proposals...

1. Assign the keys when you first start RetroArch. EmulationStation style.

2. Retropad that invisible ... that the "GUI" automatic configuration profiles have, as have the core.
- Xbox360 (A - OK, Cancel B)
- PSX (X - OK, Tringlulo - Cancel)
- Generic Control and others.

**Comment by fr500** [comment]
@tony971 the other suggestion is acceptable, use retropad labels (or the descriptors for the retropad buttons) when available, someone might look at it sometime.

But please stop opening the issue to change this behavior in every way you think off everywere, it gets really annoying.
