### ISSUE TITLE
some sort of semi autoconfig

### ISSUE THREAD

**Issue by moTechPlz** [libretro/retroarch-joypad-autoconfig#214]
The problem is retrolink and maybe other sell different controllers with the same product ids. It is not possible to distinguish them by software.

I propose for these cases after an autoconfig is matched by vendor and product id to ask the user to press for instance A and then switch between config sets by returned scancode accordingly.

Or maybe a popup menu saying 'x brand controller detected'' and select between N64, GameCube, etc type.

**Comment by RobLoach** [comment]
Been >4 years since this was opened. Going to close it for now. Thanks!
