### ISSUE TITLE
Mocute_Bluetooth_Remote 2 joysticks same player

### ISSUE THREAD

**Issue by douglasjam** [libretro/retroarch-joypad-autoconfig#223]
I'm a bit losted, I tried so many configurations and tutorials and could not get my retropie to work properly.

I have 2 Mocute Bluetooth joysticks. (http://eud.dx.com/product/wireless-bluetooth-game-controller-joystick-for-smartphone-black-844428477)

I configured both in one single dongle via bluetooth.
Configura everything properly.

But joystick 1 and 2 controls only player 2, I could not make player 2 to work.

Here are my config:

/opt/retropie/configs/all/retroarch.cfg

`input_player1_joypad_index` = 0
input_player1_a = 1
input_player1_b = 2
input_player1_y = 4
input_player1_x = 3
input_player1_start = 0
input_player1_select = 5
# input_player1_l = "q"
# input_player1_r = "w"

input_player1_left = "left"
input_player1_right = "right"
input_player1_up = "up"
input_player1_down = "down"

input_player2_joypad_index = 1
input_player2_a = 1
input_player2_b = 2
input_player2_y = 4
input_player2_x = 3
input_player2_start = 0
input_player2_select = 5
input_player2_left = "left"
input_player2_right = "right"
input_player2_up = "up"
input_player2_down = "down"`

/etc/udev/rules.d/10-local.rules AND /etc/udev/rules.d/99-bluetooth.rules (same config)
`
SUBSYSTEM=="input", ATTRS{name}=="MOCUTE-036_B50-AC10", MODE="0666", ENV{ID_INPUT_JOYSTICK}="0"
SUBSYSTEM=="input", ATTRS{name}=="MOCUTE-036_B50-BB62", MODE="0666", ENV{ID_INPUT_JOYSTICK}="1"
`

Also tried the configuration below but nothing.

https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/Mocute_Bluetooth_Remote.cfg

**Comment by hizzlekizzle** [comment]
Sometimes identical pads will both get stuck controlling the same player. You can usually resolve this by going into settings > p2 input binds and changing the device index to use the other pad (they should be enumerated as #1 and #2).

**Comment by douglasjam** [comment]
no success =/

what I did that saw some strange behaviour is:

/etc/udev/rules.d/10-local.rules

`
SUBSYSTEM=="input", ATTRS{name}=="MOCUTE-036_B50-AC10", MODE="0666", ENV{ID_INPUT_JOYSTICK}="1"
 SUBSYSTEM=="input", ATTRS{name}=="MOCUTE-036_B50-BB62", MODE="0666", ENV{ID_INPUT_JOYSTICK}="1" 
`

changed to 1 in both, and then while configuring the input in emulation station it says 2 gamepads, i configured both, but while playing, player 2 stills controlling player 1 also =/.
but the start button "seems to be working isolated"

**Comment by RobLoach** [comment]
Is this still an issue? Feel free to make a new issue if you're having issues with Mocute. It would need the vendor and device id.
