### ISSUE TITLE
Steam Controller issues - B button crashes games/menu items with RetroArch.

### ISSUE THREAD

**Issue by mdeguzis** [libretro/retroarch-joypad-autoconfig#225]
My Steam controller is just using a default gamepad profile that mimics the Xbox 360 controller. I can confirm everything works fine with a keyboard doing the same actions. I can use my Xbox 360 controller without problems. Has to be the Steam Controller. 
1. Input config menu with B
2. Starting game with B
- Log: http://sprunge.us/CZdM
- Reddit discussion: [[Link 1](https://www.reddit.com/r/linux_gaming/comments/4lkbhb/steam_controller_not_working_with_sdl1_based)]
- [lsusb](https://gist.github.com/ProfessorKaos64/5d19bc61d93ea3a41192d483b13ee37b)

**Possible workaround:**

> For what it's worth, Retroarch works great with the steam controller aside from the B button causing it to crash for some reason (it's a known bug from what I've seen). In the steam controller settings I've mapped the B button to a keyboard button and haven't had the crashing problem since.

**Notes**

It seems there are conflicting [raw input](https://github.com/libretro/retroarch-joypad-autoconfig/blob/f7f610787b99ed429ff0ac443cdaa1ae473a6b2e/linuxraw/Steam_Controller.cfg) assignments of button id 0:

```
input_b_btn = "0"
input_l3_btn = "0"
```

I haven't had time to test the IDs with `evtest` yet. @RobLoach , mind taking a look at your commited udev and raw input files? There seems to be duplicate assignments for b_btn, y_btn, 13_btn, and r3_btn. If I get time today i'll check (edit: I see now, for the triggers). 

Maybe it's due to how the device is identified? One starting RetroArch, the Steam Controller is identified as an Xbox 360 pad.

**Comment by ProfessorKaos64** [comment]
Update: the vendor ID is wrong:

```
  idVendor           0x28de (hex) 10462 (decimal)
  idProduct          0x1142 (hex) 4418  (decimal)
```

Where as the config file has:

```
input_vendor_id = 10462
input_product_id = 1142
```

**Comment by fr500** [comment]
That wouldn't cause a crash

**Comment by ProfessorKaos64** [comment]
I'm not sure then, but it is definitely the wrong ID. I launched RetroArch with --verbose, but couldn't see anything of value (to me). I'll try retroarch-dbg later to see if it gives me anything more. It's strange that (per the Reddit post above), remapping B to a keyboard button with the steam controller, and subsequently the input in RetroArch, fixes this issue. hmm.

**Comment by fr500** [comment]
The ID is correct for an XBOX 360 controller

**Comment by Kivutar** [comment]
Or your controller is acting in keyboard mode, and the key is emulating escape.

**Comment by ProfessorKaos64** [comment]
The key is mapped only to A/B/X/Y through the Steam Controller interface. I believe I can double check with evtest. Even if it isn't causing the crash, the product id should be 4418 for the Steam Controller, not 1142. And I disagree with the key emulating escape. You can traverse the menu fine for most areas, it only crashes on certain things (per the OP), which makes diagnosing this difficult. Is there any debugging practices I can pursue beyond tools for evdev?

**Comment by glodfinch** [comment]
The issue is as Kivutar said, that it's starting in keyboard mode, where B is mapped to esc. To fix I installed https://github.com/ynsta/steamcontroller and ran `sc-xbox.py start`. This causes it to emulate an XBOX 360 controller and it seems to work fine.

**Comment by ProfessorKaos64** [comment]
I would want to argue there ought to be a way to block that key using device detection over the joypad-autoconfig udev rules. Steam/SteamOS is sending A/B/X/Y, but it is sent across as a generic xinput device (or so I thought). Many games that are Xbox 360 controller friendly utilize the controller fine, so there must be a way to interpret the controller more effectively.
