### ISSUE TITLE
Xbox One Controller with latest driver and Wireless Adapter on Win10 being detected as generic "Xinput Controller" + Guide Button not working

### ISSUE THREAD

**Issue by Ryunam** [libretro/retroarch-joypad-autoconfig#229]
As indicated in the title, the latest driver available for the Xbox One controller on Windows 10 seem to make Retroarch not detect it properly when it's connected through the Wireless adapter. Instead, it is seen as a generic "Xinput controller". 
I still have to confirm whether the input bindings automatically assigned by Retroarch work in their entirety anyway, regardless of the name of the autoconfig that Retroarch calls, but I can confirm that with the old drivers on Windows 7 Retroarch detected it properly as an "Xbox One controller on Windows".

Moreover, there is an issue with the Guide Button on Retroarch not working at all on Windows 10 once again with the latest drivers, printing a "Null" OSD message with every button press. 
This probably happens because of the Windows 10 driver "locking" that button for their OS-level GameDVR features, but even by deactivating that and uninstalling the Xbox app entirely the issue persists in RA.

**Comment by EndZz-** [comment]
Has this been fixed? I'm having the same issue right now, detected the the controller then when I chose bind it wouldn't detect input.

**Comment by fr500** [comment]
This is a Windows Driver issue.
I'm on the current insider and it works perfectly fine for me.

The guide button is in fact because of GameDVR. If you disable that it works fine.

**Comment by EndZz-** [comment]
Thank you that got it working!!!
