### ISSUE TITLE
Xbox 360 Control - No auto configure.

### ISSUE THREAD

**Issue by alexb3d** [libretro/retroarch-joypad-autoconfig#233]
Hi.
Ubuntu LTS + RetroArch Testing. (New Installation)

Recognizes, Xbox 360 Control. No auto configure the control.

**Comment by hizzlekizzle** [comment]
Did you also download the retroarch-assets package? I think it contains the autoconfig profiles.

**Comment by alexb3d** [comment]
Yes, I have installed. I installed this way

> sudo add-apt-repository ppa:libretro/testing -y; sudo apt update; sudo apt install retroarch retroarch-* libretro-* -y

Right at this moment I'm updating.
And the package is being updated "retroarch-assets package". Taste and comment.

**Comment by alexb3d** [comment]
Updated "retroarch-assets 0.1+r132", still does not work.
image https://yadi.sk/i/PubtJ8nBvE3Qn

**Comment by hizzlekizzle** [comment]
Looks like it's reporting as something that we don't have a profile for yet. You could make one and submit it, if you like.

**Comment by alexb3d** [comment]
Does not matter. I can set it manually. I just wanted to report the bug.
It is rare, a month ago I installed the testing. If you configured automatically.

**Comment by Kivutar** [comment]
You're using a special dongle? You can generate an autoconfig file once the manual binding works. Then paste it there and we will add it to our repo.

**Comment by alexb3d** [comment]
> You're using a special dongle?

Do not.

> You can generate an autoconfig file

Is this what you ask? retroarch.cfg https://yadi.sk/d/UWvJ5Vz3vGZWL

* A note. I have a "microsoft wireless keyboard 800" keyboard. Linux recognizes it as a control. When the keyboard is in the USB 1 port. RetroArch configure the keyboard as a control. I have to put on a low port. https://yadi.sk/i/nwEDnCMAvGZZy

**Comment by MrXCuci** [comment]
input_driver = "android"
input_device = "Xbox 360 Wireless Adapter"
input_device_display_name = "XBOX 360 Wireless Controller"
input_vendor_id = "1118"
input_product_id = "1817"
input_b_btn = "97"
input_y_btn = "100"
input_select_btn = "109"
input_start_btn = "108"
input_up_btn = "h0up"
input_down_btn = "h0down"
input_left_btn = "h0left"
input_right_btn = "h0right"
input_a_btn = "96"
input_x_btn = "99"
input_l_btn = "102"
input_r_btn = "103"
input_l2_axis = "+6"
input_r2_axis = "+7"
input_l3_btn = "106"
input_r3_btn = "107"
input_l_x_plus_axis = "+0"
input_l_x_minus_axis = "-0"
input_l_y_plus_axis = "+1"
input_l_y_minus_axis = "-1"
input_r_x_plus_axis = "+2"
input_r_x_minus_axis = "-2"
input_r_y_plus_axis = "+3"
input_r_y_minus_axis = "-3"
input_b_btn_label = "B"
input_y_btn_label = "Y"
input_select_btn_label = "Back"
input_start_btn_label = "Start"
input_up_btn_label = "D-Pad Up"
input_down_btn_label = "D-Pad Down"
input_left_btn_label = "D-Pad Left"
input_right_btn_label = "D-Pad Right"
input_a_btn_label = "A"
input_x_btn_label = "X"
input_l_btn_label = "Left Bumper"
input_r_btn_label = "Right Bumper"
input_l2_axis_label = "Left Trigger"
input_r2_axis_label = "Right Trigger"
input_l3_btn_label = "Left Stick"
input_r3_btn_label = "Right Stick"
input_l_x_plus_axis_label = "Left Analog X+"
input_l_x_minus_axis_label = "Left Analog X-"
input_l_y_plus_axis_label = "Left Analog Y+"
input_l_y_minus_axis_label = "Left Analog Y-"
input_r_x_plus_axis_label = "Right Analog X+"
input_r_x_minus_axis_label = "Right Analog X-"
input_r_y_plus_axis_label = "Right Analog Y+"
input_r_y_minus_axis_label = "Right Analog Y-"
