### ISSUE TITLE
Tomee Nes to USB config

### ISSUE THREAD

**Issue by misterericman** [libretro/retroarch-joypad-autoconfig#234]
Hey Internet,

I am a big noob.  I am trying to get this thing I ordered from amazon to work with retroarch, but when the core loads in launchbox, it says that there is no controller config.  I have tried to load a few different autoconfig files from the udev folder, but nothing seems to work.  Please Help me!
-Eric

**Comment by hizzlekizzle** [comment]
If there's no autoconfig already, you'll need to go to settings > input > p1 input binds > bind all. From there, you can also save an autoconfig profile and submit it here for inclusion.

**Comment by misterericman** [comment]
it just times out :(

**Comment by misterericman** [comment]
It would be tremendous if there was a video tutorial.  I, for whatever reason, am struggling.

**Comment by misterericman** [comment]
user 1 analog to digital type should be set to left or right?  Device type should be set to?  The device index recognizes the nes pc game pad, but for some reason the button presses aren't being recorded

**Comment by RobLoach** [comment]
> user 1 analog to digital type should be set to left or right?

Left

>Device type should be set to? The device index recognizes the nes pc game pad, but for some reason the button presses aren't being recorded

Usually the default is best. You could try a few others, and switch it in retroarch.cfg if you run into issues. Deleting `input_driver` in retroarch.cfg will reset it to default.
