### ISSUE TITLE
NYKO Core Controller

### ISSUE THREAD

**Issue by lasers** [libretro/retroarch-joypad-autoconfig#238]
I whipped out my Nyko Core controller to make this.
`'  USB Controller.cfg'`

```
input_device = "  USB Controller"
input_driver = "udev"
input_vendor_id = "1356"
input_product_id = "616"

input_up_btn = "4"
input_down_btn = "6"
input_left_btn = "7"
input_right_btn = "5"

input_a_btn = "13"
input_b_btn = "14"
input_x_btn = "12"
input_y_btn = "15"

input_l_btn = "10"
input_r_btn = "11"
input_l2_btn = "8"
input_l3_btn = "1"
input_r2_btn = "9"
input_r3_btn = "2"

input_l_x_plus_axis = "+0"
input_l_x_minus_axis = "-0"
input_l_y_plus_axis = "+1"
input_l_y_minus_axis = "-1"
input_r_x_plus_axis = "+2"
input_r_x_minus_axis = "-2"
input_r_y_plus_axis = "+3"
input_r_y_minus_axis = "-3"

input_select_btn = "0"
input_start_btn = "3"
input_menu_toggle_btn = "16"

input_up_btn_label = "D-Pad Up"
input_down_btn_label = "D-Pad Down"
input_left_btn_label = "D-Pad Left"
input_right_btn_label = "D-Pad Right"

input_a_btn_label = "Circle"
input_b_btn_label = "Cross"
input_x_btn_label = "Triangle"
input_y_btn_label = "Square"

input_l_btn_label = "L1"
input_r_btn_label = "R1"
input_l2_btn_label = "L2"
input_r2_btn_label = "R2"
input_l3_btn_label = "L3"
input_r3_btn_label = "R3"

input_l_x_plus_axis_label = "Left Analog Right"
input_l_x_minus_axis_label = "Left Analog Left"
input_l_y_plus_axis_label = "Left Analog Down"
input_l_y_minus_axis_label = "Left Analog Up"
input_r_x_plus_axis_label = "Right Analog Right"
input_r_x_minus_axis_label = "Right Analog Left"
input_r_y_plus_axis_label = "Right Analog Down"
input_r_y_minus_axis_label = "Right Analog Up"

input_select_btn_label = "Select"
input_start_btn_label = "Start"
input_menu_toggle_btn_label = "Home"
```
This controller have everything (http://nyko.com/products/playstation-3-core-controller) so I mapped everything without any problem. If given an option, I would opt for this over official Playstation 3 controller. It is very comfortable, sturdy, and comes with a 9 foot USB cord. 

Setting up this controller can be problematic sometimes as it was made for PS3 system (See the FAQ on link above). Try all USB ports first before giving up.

This configuration is not for me, is optional, and is for RetroArch community.

**Comment by hizzlekizzle** [comment]
Hey, thanks for submitting this! It looks like it matches one of our existing PS3 configuration files, though, so we'll stick with it.

**Comment by lasers** [comment]
To confirm this existing PS3 configuration file, it works perfectly out of the box. I was too focused on making a config for this controller (right after Microsoft Duke controller) without realizing/checking/testing. I also plugged this baby in few first bad USB ports which does not work right out of the box for me so I had mixed results. Thank you!
