### ISSUE TITLE
User 0 Save Autoconfig -- Writing back differently. 

### ISSUE THREAD

**Issue by lasers** [libretro/retroarch-joypad-autoconfig#239]
This feature does not always save back to the same file it snagged the joypad config from... in because of different input_device name than the file it resides in.

Retroarch auto-loads `'Microsoft_X-Box_360_pad.cfg'`.

```
input_device = "Microsoft X-Box 360 pad"
input_driver = "udev"
input_vendor_id = 1118
input_product_id = 654

input_b_btn = "0"
input_y_btn = "2"
input_select_btn = "6"
input_start_btn = "7"
input_up_btn = "h0up"
input_down_btn = "h0down"
input_left_btn = "h0left"
input_right_btn = "h0right"
input_a_btn = "1"
input_x_btn = "3"
input_l_btn = "4"
input_r_btn = "5"
input_l2_axis = "+2"
input_r2_axis = "+5"
input_l3_btn = "9"
input_r3_btn = "10"
input_l_x_plus_axis = "+0"
input_l_x_minus_axis = "-0"
input_l_y_plus_axis = "+1"
input_l_y_minus_axis = "-1"
input_r_x_plus_axis = "+3"
input_r_x_minus_axis = "-3"
input_r_y_plus_axis = "+4"
input_r_y_minus_axis = "-4"
input_menu_toggle_btn = "8"

input_b_btn_label = "A"
input_y_btn_label = "X"
input_select_btn_label = "Back"
input_start_btn_label = "Start"
input_up_btn_label = "D-Pad Up"
input_down_btn_label = "D-Pad Down"
input_left_btn_label = "D-Pad Left"
input_right_btn_label = "D-Pad Right"
input_a_btn_label = "B"
input_x_btn_label = "Y"
input_l_btn_label = "LB"
input_r_btn_label = "RB"
input_l2_axis_label = "LT"
input_r2_axis_label = "RT"
input_l3_btn_label = "Left Thumb"
input_r3_btn_label = "Right Thumb"
input_l_x_plus_axis_label = "Left Analog Right"
input_l_x_minus_axis_label = "Left Analog Left"
input_l_y_plus_axis_label = "Left Analog Down"
input_l_y_minus_axis_label = "Left Analog Up"
input_r_x_plus_axis_label = "Right Analog Right"
input_r_x_minus_axis_label = "Right Analog Left"
input_r_y_plus_axis_label = "Right Analog Down"
input_r_y_minus_axis_label = "Right Analog Up"
input_menu_toggle_btn_label = "Guide"
```

I swapped two buttons and applied "User 1 Save Autoconfig" only to get `'Microsoft X-Box 360 pad.cfg'` (without underlines).

The new save autoconfig will contain something like this.

```
input_driver = "udev"
input_device = "Microsoft X-Box 360 pad"
input_vendor_id = "1118"
input_product_id = "654"
input_up_btn = "h0down"
input_down_btn = "h0up"
```

Next time I run RetroArch, I only can use two buttons on the controller as everything else not configured won't be in the new save autoconfig. This can be bad for Lakka and others.

**Comment by fr500** [comment]
you have to map everything.

**Comment by lasers** [comment]
It's not the question of mapping everything. It's more about writing back differently.

>This feature does not always save back to the same file it snagged the joypad config from... in because of different input_device name than the file it resides in.

>Retroarch auto-loads 'Microsoft_X-Box_360_pad.cfg'.

>I swapped two buttons and applied "User 1 Save Autoconfig" only to get 'Microsoft X-Box 360 pad.cfg' (without underlines).

Microsoft_X-Box_360_pad.cfg
Microsoft X-Box 360 pad.cfg (without underlines).

**Comment by fr500** [comment]
You are not understanding.
Most of those files are not saved with the tool, the files were done by hand till I wrote the save function.

**Comment by lasers** [comment]
How does it recognize the controller? How does RetroArch know which file to load? What is it looking for? You're saying that it does not matter how the files are named?

**Comment by fr500** [comment]
Yes it doesn't matter at all.
It uses a scoring process checks the files one by one, checks different parameters and assigns weighted values.

**Comment by lasers** [comment]
Ah I see. Okay thanks, pal. Have a happy Thanksgiving. :-)
