### ISSUE TITLE
README and CONTRIBUTING information

### ISSUE THREAD

**Issue by CoalaJoe** [libretro/retroarch-joypad-autoconfig#322]
Would be great if the structure of this repo would be explained.

**Comment by hizzlekizzle** [comment]
Yeah, that's true. If you would be interested in writing something up, I'll merge it.

**Comment by CoalaJoe** [comment]
I can try. But I don't know how or/and where to add what config file.

**Comment by manuti** [comment]
How I can add the .cfg file for a new device (Gioteck VX2 Wired Controller.cfg) is working in my Lakka on Orange Pi and I want to share the configuration.
Thanks

**Comment by gouchi** [comment]
@manuti : please read [this documentation](http://www.lakka.tv/doc/Contributing-your-joypad-config). Thank you.

**Comment by MatiasFernandez** [comment]
@hizzlekizzle should this be closed?
