### ISSUE TITLE
xbox one pad firmware 2015

### ISSUE THREAD

**Issue by Promises** [libretro/retroarch-joypad-autoconfig#332]
its not added, cant be arsed to fork and send pr.

input_driver = "udev"
input_device = "Microsoft X-Box One pad (Firmware 2015)"
input_vendor_id = "1118"
input_product_id = "733"
input_b_btn = "0"
input_y_btn = "2"
input_select_btn = "6"
input_start_btn = "7"
input_up_btn = "h0up"
input_down_btn = "h0down"
input_left_btn = "h0left"
input_right_btn = "h0right"
input_a_btn = "0"
input_x_btn = "3"
input_l_btn = "4"
input_r_btn = "5"
input_l2_axis = "+2"
input_r2_axis = "+5"
input_l3_btn = "9"
input_r3_btn = "10"
input_l_x_plus_axis = "+0"
input_l_x_minus_axis = "-0"
input_l_y_plus_axis = "+1"
input_l_y_minus_axis = "-1"
input_r_x_plus_axis = "+3"
input_r_x_minus_axis = "-3"
input_r_y_plus_axis = "+4"
input_r_y_minus_axis = "-4"

**Comment by fr500** [comment]
Then we can't be arsed to merge
