### ISSUE TITLE
"Duplicate" config files causing weird issues

### ISSUE THREAD

**Issue by barbudreadmon** [libretro/retroarch-joypad-autoconfig#339]
Having 2 files containing the same config for your controller seems to cause issues : 

https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/Sony-PlayStation3-DualShock3-Controller-Bluetooth.cfg and https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/Sony-PlayStation3-DualShock3-Controller-USB.cfg contains the same config, having both at the same time in the autoconfig directory caused my dualshock3 to stop working properly. I noticed it after upgrading retroarch to 1.5 and my linux kernel to 4.9 (i think the device was renamed from "Sony Computer Entertainment Wireless Controller" to "PLAYSTATION(R)3 Controller" with this kernel, which is why i didn't have this issue before). I'm using native kernel+bluez support, no sixad daemon.

**Comment by fr500** [comment]
Weird, but what's the issue? what happens specifically?

**Comment by barbudreadmon** [comment]
The mapping didn't work, pressing buttons on my controller produced random result (d-pad adding coins in fbalpha, "fire" buttons moving my character, and such). Removing the duplicate solved this. I think you can easily reproduce this behavior by duplicating the config file for a controller you are using.

**Comment by fr500** [comment]
Hmmm I just tried but nothing happened... it actually looks for one config (the best one) and uses that one config...

**Comment by Kivutar** [comment]
Yeah there can't be a bug with this. If your device name is "Sony PLAYSTATION(R)3 Controller", this one will be used https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/Sony-PlayStation3-DualShock3-Controller-USB.cfg If it is "PLAYSTATION(R)3 Controller", this one will be used https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/Sony-PlayStation3-DualShock3-Controller-Bluetooth.cfg

The only bug we can imagine is if you're using an old kernel that attributes a wrong device name.

**Comment by fr500** [comment]
Ok then I guess the problem is it always picks the LAST MATCH with the highest score.
So probably it picked the bad one.

**Comment by Kivutar** [comment]
But the two files can't have the same score, since the device_name differs.

**Comment by bootsector** [comment]
I've faced DS3/BT issues when I updated RA in my emulation box. Not sure if this is related. Any help is appreciated.

https://github.com/libretro/RetroArch/issues/5063

**Comment by RobLoach** [comment]
There aren't any more duplicate vendor/device IDs.
