### ISSUE TITLE
8Bitdo Controllers autoconfig using wrong VID & PID

### ISSUE THREAD

**Issue by ctwohig** [libretro/retroarch-joypad-autoconfig#351]
I had a problem with the 8Bitdo N64 and SNES30 controllers being detected as the NES30 Pro when using bluetooth, usb worked correctly.  after digging into it i found the PID and VID in the autoconfig files do not appear to be correct

the N64 controller using bluetooth shows the following device info
_RetroArch [INFO] :: Device #0 PID: {3830} VID:{2DC8}_

hex 3830 = dec 14384 and hex 2DC8 = dec 11720

the config file for this controller shows
_input_vendor_id = 14384
input_product_id = 9_

the input vendor id matches what i'm seeing as the PID, when i switch them with what i have as the correct decimal values all controllers are detected as they should be.  i also looked at the usb config files, and even though they were working, they were showing the wrong id's as well.  I'm uploading a log file with the output from each controller i have when connected with Bluetooth and USB, as well as the updated autoconfig files that seem to be working.  i also have a feeling the other config files for 8Bitdo aren't correct but i don't have all their controllers to test

The controllers i do have are on the latest firmware as of today
N64            v2.0
SNES30      v4.0
NES30 Pro  v4.0

[8Bitdo_RetroArch_Logs.txt](https://github.com/libretro/retroarch-joypad-autoconfig/files/1086386/8Bitdo_RetroArch_Logs.txt)
[xinput.zip](https://github.com/libretro/retroarch-joypad-autoconfig/files/1086388/xinput.zip)

**Comment by fr500** [comment]
then they may have changed the IDs again, mine work fine.

**Comment by ctwohig** [comment]
agreed, i just received an NES30 and updated it to the 4.0 firmware and it also appears to have been changed.  there also doesn't appear to be a specific file for the NES30 bluetooth so i created one.  I'm attaching another set of files that includes the NES30 as well as the others i submitted last week

[xinput.zip](https://github.com/libretro/retroarch-joypad-autoconfig/files/1086377/xinput.zip)
[8Bitdo_RetroArch_Logs.txt](https://github.com/libretro/retroarch-joypad-autoconfig/files/1086381/8Bitdo_RetroArch_Logs.txt)

**Comment by RobLoach** [comment]
Been a bunch of updates to 8bitdo VID/PIDs. Feel free to open up a new issue if htere's an issue.
