### ISSUE TITLE
Switch Pro Controller analog sticks not working correctly

### ISSUE THREAD

**Issue by JosephTico** [libretro/retroarch-joypad-autoconfig#353]
On Mario 64 seems like only the left and down directions work on the left analog stick.

**Comment by duganchen** [comment]
Is this still happening? The vid and pid on the Switch Pro Controller profile was fixed a few days ago:

https://github.com/libretro/retroarch-joypad-autoconfig/commit/1e7e38e3fe505498042ae1872170f3e518dc9382#diff-637ac2ab50e1180e27d7a95227a5b1dd

**Comment by RobLoach** [comment]
The Switch Pro Controller configs were updated. Create a new issue if you still have a problem.
