### ISSUE TITLE
Microsoft_X-Box_One_S_pad_v2.cfg is certainly invalid

### ISSUE THREAD

**Issue by Alex131089** [libretro/retroarch-joypad-autoconfig#376]
Due to https://github.com/libretro/RetroArch/issues/3903, the udev/Microsoft_X-Box_One_S_pad_v2.cfg configuration is probably invalid, the file VID&PID is the one from ASUS (http://www.the-sz.com/products/usbid/index.php?v=0xB05&p=17CB).
Example : https://gist.github.com/Alex131089/2d8418a27164e78b1cf5b5881680332c
2578:1 (http://www.the-sz.com/products/usbid/index.php?v=0x0A12) reported instead of 1118:765 (Xbox One S using BT, reported as 746 using USB)

**Comment by hizzlekizzle** [comment]
Oh no, that's a big problem! Do you have a correct vid/pid for it?

**Comment by Alex131089** [comment]
All I can tell, is that the BT vid:pid for the corresponding USB vid:pid 1118:746 is 1118:765 (which is probably what was trying to be achieved).

However, between https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/Microsoft_X-Box_One_S_pad.cfg and https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/Microsoft_X-Box_One_S_pad_v2.cfg the configuration is not the same, so it's maybe another controller, or the BT mapping is different from the USB one (I don't believe it is), or it is another/custom configuration (more likely ?).

**Comment by duganchen** [comment]
The values are vid:1118,pid:736. I was the one who added that profile, and those are the values for that controller (I just checked).

This issue can be resolved now, btw. It was fixed with the merge of https://github.com/libretro/retroarch-joypad-autoconfig/pull/409.
