### ISSUE TITLE
Problem with joypad autoconfig

### ISSUE THREAD

**Issue by mdk87** [libretro/retroarch-joypad-autoconfig#377]
Hello to everyone. I installed retroarch on my androidtvbox, the problem is that when I open it I leave a message "not configured, using fallback" In the list of config files I found the .cfg file compatible with my gamepad. Now the question is? do I copy this text in retroarch.cfg? because when I go to search input_device, input_driver, input_vendor_id in retroarch.cfg does not find them, so I can not set the values. suggestions? only d-pad work

**Comment by hizzlekizzle** [comment]
Where did you find the one that matches your device? is it in the 'android' subdirectory or somewhere else? If somewhere else, you can try copying it into the 'android' subdir and see if it gets picked up, but the other driver may or may not map the same as the android input driver.

**Comment by mdk87** [comment]
i found in the android subdirectory. I used retroarch on libreELEC, everything installed in automatic .. now that i have an androidboxtv i want to install it here. but I have this problem of recognizing the gamepad. these .cfg files where to put them?

**Comment by hizzlekizzle** [comment]
They go into your autoconfig/android directory. You can go to settings > directory and see where it's looking for them. If it's pointing into /data/data/com.retroarch/whatever, you might try making a new folder in your local-storage/RetroArch directory and point it toward that instead. Then, go to the online updater and re-download the autoconfig profiles (they'll populate the new autoconfig directory)

**Comment by mdk87** [comment]
I tried but nothing. in the folder when I unload profiles is always empty .. I noticed that even the box remote control does not recognize. While using an app from the phone emulating the remote control works. ah the gamepad I use to connect it via usb. is it so difficult to configure this retroarch? D:

**Comment by hizzlekizzle** [comment]
So you're saying when you follow the steps from my post above, the directory remains empty? If so, that sounds like a permissions issue, so make sure you're using a directory on your device's internal storage.

**Comment by mdk87** [comment]
it remains empty. down says it downloads and extracts but when i go to the set folder it is empty. it's strange because when I installed the app i gave the authorizations .. i also checked manually

**Comment by hizzlekizzle** [comment]
Ok, yeah, it sounds like there's something weird going on with your permissions, then. In that case, just copy the files into the appropriate directory manually. You can download them from http://buildbot.libretro.com/assets/frontend/autoconfig.zip

**Comment by mdk87** [comment]
I'm in doubt ... but should the device have root permissions? because if I try to search those folders inside the archive autoconfig.zip does not find them, even if the hidden files are active .. while backwards if I go in the directories there are but they are all empty. If I follow the folder path as in the backend program I can not find them with the file manager. I'm definitely wrong with something

**Comment by hizzlekizzle** [comment]
The device shouldn't need root, no.

If you've created an autoconfig directory inside storage/RetroArch and then made that your autoconfig directory in settings > directory, you should be able to just put the contents of the autoconfig.zip archive into that directory.

**Comment by mdk87** [comment]
I was able to connect the gamepad. in retroarch settings it detects it connected via usb thing it did not do before. now the problem is mapping the keys because only the dpad and the analogs work. Is it a way to set the a, b keys manually?

**Comment by hizzlekizzle** [comment]
If you use a keyboard to get to settings > input > p1 input binds, are you able to bind the buttons there?

**Comment by FacundoARG** [comment]
Hi, I have the same issue on my MxQ 4k Pro (plus)  tv box Android 6. Like mdk87, I can navigate with my Generic USB Genesis Joystick, Xbox One S Joystick and even with a keyboard; but the a,b buttons does not work :( . 
I have tested the over an other MxQ (Android 5.1) and works perfectly. I think there is an issue with Android 6, any suggestion?

**Comment by mdk87** [comment]
no because only the direction keys work. so I was wondering if there was another way. at least set only the selection key so then i can do it in the program

**Comment by hizzlekizzle** [comment]
Does it say the game pad is "configured" or "not configured"? If not configured, you can try to save an autoconfig profile with just the directions and then try to guess/infer what the other buttons would be and enter those values into the autoconfig file manually. That's a pretty unpleasant way to do it, though.

**Comment by mdk87** [comment]
Does it say dragonrise generic PlayStation gamepad configured in port #2. 
then I open the .cfg file of the controller and try to edit the values ​​from them?

**Comment by mdk87** [comment]
This is the file .cfg
# 0079:0011 DragonRise Inc. Gamepad

# There are a number of controllers that all share the same generic USB
# encoder chip and therefor identify themselves the same.
# Most share a common layout modeled after the original PlayStation gamepad,
# but there are variations such as the "Retrolink Sega Saturn USB GamePad" that
# are vastly different.
# It seems that some variations swap L with L2 and R with R2
# This configuration file follows the mapping that is most commonly used by
# gamepads in general. (action buttons enumerated clockwise)
# 1 2 3 4 L R L2 R2 Se St

input_driver = "android"
input_vendor_id = 121
input_product_id = 17
input_device = "USB Gamepad "
input_device_display_name = "DragonRise generic PlayStation gamepad"

#########

input_x_btn = "0"
input_a_btn = "1"
input_b_btn = "2"
input_y_btn = "3"
input_l_btn = "4"
input_r_btn = "5"
input_l2_btn = "6"
input_r2_btn = "7"
input_select_btn = "8"
input_start_btn = "9"

input_left_axis = "-0"
input_right_axis = "+0"
input_up_axis = "-1"
input_down_axis = "+1"

#########

input_x_btn_label = "1/Triangle"
input_a_btn_label = "2/Circle"
input_b_btn_label = "3/Cross"
input_y_btn_label = "4/Square"
input_l_btn_label = "L1"
input_r_btn_label = "R1"
input_l2_btn_label = "L2"
input_r2_btn_label = "R2"
input_select_btn_label = "Select"
input_start_btn_label = "Start"

input_left_btn_label = "D-Pad Left"
input_right_btn_label = "D-Pad Right"
input_up_btn_label = "D-Pad Up"
input_down_btn_label = "D-Pad Down

**Comment by RobLoach** [comment]
I'm closing this. Get on discord if you're looking for support on how to grab the latest autoconfigs.
