### ISSUE TITLE
How Do I Work These?

### ISSUE THREAD

**Issue by Yo-Cookie** [libretro/retroarch-joypad-autoconfig#384]
Where Do I Put It And Stuff Like That?
I've Been Stuck On This For 3 HOURS!
Please Help!
I'm Using A Mayflash Gamecube Adapter If You're Wondering

**Comment by hizzlekizzle** [comment]
These should come with your RetroArch installation. However, you can refresh them by going to the online updater and downloading the autoconfig profiles again. It will automatically use the ones for the current input driver.
