### ISSUE TITLE
OK and cancel are swapped when a remote controller is detected

### ISSUE THREAD

**Issue by Oibaf66** [libretro/retroarch-joypad-autoconfig#400]
I have already opend this issue in the Retroarch project. 

When a remote control is detected as first controller, the OK and cancel are swapped for all the other controllers inserted after the remote controller. When the remote controller is inserted as second controller the OK and cancel are not swapped for the remote controller as it should be.
This behaviour is very clear from the code:

**task_autodetect.c**

if (string_is_equal_fast(device_type, "remote", 6))
   {
      static bool remote_is_bound        = false;
      snprintf(msg, sizeof(msg), "%s configured.",
            (string_is_empty(display_name) &&
             !string_is_empty(params->name)) ? params->name : (!string_is_empty(display_name) ? display_name : "N/A"));

 if (!remote_is_bound)
      {
         task_free_title(task);
         task_set_title(task, strdup(msg));
      }
      remote_is_bound = true;
      if (params->idx == 0)
         input_autoconfigure_swap_override = true;
   }

**menu_event.c** 

 bool input_swap_override                = input_autoconfigure_get_swap_override();
   unsigned menu_ok_btn                    = (!input_swap_override && 
      settings->bools.input_menu_swap_ok_cancel_buttons) ?
      RETRO_DEVICE_ID_JOYPAD_B : RETRO_DEVICE_ID_JOYPAD_A;

   unsigned menu_cancel_btn                = (!input_swap_override && 
      settings->bools.input_menu_swap_ok_cancel_buttons) ?
      RETRO_DEVICE_ID_JOYPAD_A : RETRO_DEVICE_ID_JOYPAD_B;

**Comment by RobLoach** [comment]
What controller? Should this be an issue for RA instead of the autoconfigs? Thanks!
