### ISSUE TITLE
DragonRise and Dialog GP-A11 clash

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/retroarch-joypad-autoconfig#407]
There's a clash between these 3 joypads (same vendor & product ID):

https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/DragonRise_Inc.___Generic___USB__Joystick__.cfg

https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/DIALOG_GP-A11.cfg

https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/DragonRise_Inc._PC_TWIN_SHOCK_Gamepad.cfg

Mine was supposed to get the config from the first one, it's getting from DIALOG_GP-A11 instead. Weirdly, now it's showing this in lsusb:

```
Bus 003 Device 002: ID 0079:0006 DragonRise Inc. PC TWIN SHOCK Gamepad
``` 

Is this string a kernel thing? I think it was showing "DragonRise generic DualShock gamepad" when I create the first file

**Edit**: weird, I get "DragonRise Inc.   Generic   USB  Joystick  " inside RetroArch... wut

My joypad is probably that "DragonRise Inc. PC TWIN SHOCK Gamepad", and I was messing around the other file all this time o.O

**Comment by sergiobenrocha2** [comment]
Uh, it's clashing with https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/DragonRise_N64.cfg too

**Comment by hizzlekizzle** [comment]
Yeah, those pads are a mess. I don't know what to do about them.

**Comment by sergiobenrocha2** [comment]
Relevant: https://github.com/libretro/retroarch-joypad-autoconfig/issues/189#issuecomment-353977972

**Comment by sergiobenrocha2** [comment]
udev shows my joypad as "usb-DragonRise_Inc._Generic_USB_Joystick-joystick"  D:

**Comment by sergiobenrocha2** [comment]
dmesg | grep DragonRise

```
[    1.356584] usb 3-1: Manufacturer: DragonRise Inc.  
[    2.579722] input: DragonRise Inc.   Generic   USB  Joystick   as /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.0/0003:0079:0006.0001/input/input15
[    2.579862] dragonrise 0003:0079:0006.0001: input,hidraw0: USB HID v1.10 Joystick [DragonRise Inc.   Generic   USB  Joystick  ] on usb-0000:00:14.0-1/input0
[    2.579874] dragonrise 0003:0079:0006.0001: Force Feedback for DragonRise Inc. game controllers by Richard Walmsley <richwalm@gmail.com>
```

**Comment by sergiobenrocha2** [comment]
Conflicts with https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/Microntek%20%20%20%20%20%20%20%20%20%20%20%20%20%20USB%20Joystick%20%20%20%20%20%20%20%20%20%20.cfg  too

**Comment by alfrix** [comment]
in my tests the input_device matters (at least in windows)
So it should only conflict with these two

udev/DIALOG_GP-A11.cfg
udev/DragonRise_Inc.___Generic___USB__Joystick__.cfg

A quick google search reveals that the DIALOG_GP-A11 have the front buttons wrong (as xbox)

But furthermore the pads seem to have wired differently the right analog sticks

Dragonrise
```
input_r_x_plus_axis = "+2"
input_r_x_minus_axis = "-2"
input_r_y_plus_axis = "+3"
input_r_y_minus_axis = "-3"
```

Dialog
```
input_r_x_plus_axis = "+3"
input_r_x_minus_axis = "-3"
input_r_y_plus_axis = "+4"
input_r_y_minus_axis = "-4"
```
@sergiobenrocha2 please

1. Delete all the autoconfig profiles in the folder 
2. Start retroarch and assign all the buttons manually
3. Select create autoconfig profile
4. Post the created profile here

**Comment by RobLoach** [comment]
It's been more than 2 years. I'm assuming this has been fixed?
