### ISSUE TITLE
hope can support the 3rd party xbox one usb controller like power A joystick

### ISSUE THREAD

**Issue by thinker2013** [libretro/retroarch-joypad-autoconfig#410]
I use 3rd part xbox one usb controller
power A xbox compatixxxx joystick.
but not work!  

can u support it ?

**Comment by hizzlekizzle** [comment]
If we don't have a particular gamepad, we rely on users to submit profiles that they create.

**Comment by RobLoach** [comment]
Export the config, and submit as a Pull Request. Thankks!
