### ISSUE TITLE
Buttons are not correct in SMW 

### ISSUE THREAD

**Issue by logos88** [libretro/retroarch-joypad-autoconfig#412]
I have a DS4v2 wired and when I play Super Mario World with bsnes-mercury the button to run is the triangle, when it should be the square.

**Comment by hizzlekizzle** [comment]
Do other games/cores have the same issue? That is, swapped retropad-X/Y?

**Comment by RobLoach** [comment]
Issue from 3 years ago.... Still an issue? Feel free to update the DS4v2 configs in a PR if you'd like them swapped.
