### ISSUE TITLE
Question regarding handling of vendor/product ids

### ISSUE THREAD

**Issue by markand** [libretro/retroarch-joypad-autoconfig#436]
Hello

I've sent the pull request regarding the different modes of my 8Bitdo SF30 Pro controllers. There is two files in my autoconfig directory:

  - 8Bitdo_Pro_SF30_BT.cfg configured for DInput (shipped with this repository)
  - 8Bitdo_Pro_SF30_BT_X.cfg configured for XInput (in my pull request, current only in my directory)

When connecting via XInput, the product/vendors ids look different as you can see from **/proc/bus/input/devices**

    I: Bus=0005 Vendor=045e Product=02e0 Version=0903
    N: Name="8Bitdo SF30 Pro"
    P: Phys=b8:8a:60:db:b4:78
    S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.0/bluetooth/hci0/hci0:256/0005:045E:02E0.0004/input/input18
    U: Uniq=e4:17:d8:3e:fd:83
    H: Handlers=kbd event16 js0 
    B: PROP=0
    B: EV=1b
    B: KEY=3ff000000000000 0 800 0 0
    B: ABS=3003f
    B: MSC=10

So in my config file I've added the following to match only in XInput mode:

    input_vendor_id = "1118"
    input_product_id = "736"

But for some reason, when running RetroArch in verbose mode, it still picks the DInput one and I can't get it to work since codes are incompatibles:

    [INFO] [udev]: Plugged pad: 8Bitdo SF30 Pro (32903:2603) on port #0.
    [INFO] [udev]: Pad #0 (/dev/input/event16) supports 0 force feedback effects.
    [INFO] [Autoconf]: 206 profiles found.
    [INFO] [Autoconf]: selected configuration: /usr/share/libretro/autoconfig/udev/8Bitdo_Pro_SF30_BT.cfg
    [INFO] [Joypad]: Found joypad driver: "udev".

Are product/vendor ids ignored? Why does it pick the wrong one?

**Comment by hizzlekizzle** [comment]
I know there's an issue where the vid/pid of the bluetooth adapter can get picked up instead of the one from the actual pad. Is that what's happening here?

**Comment by markand** [comment]
Yes, exactly what @bparker06 said in the [related issue](https://github.com/libretro/RetroArch/issues/6325). I'll try to find a way to fix it.
