### ISSUE TITLE
8bitdo / SF30 PRO / Firmware v1.25 / mapping broken

### ISSUE THREAD

**Issue by SupervisedThinking** [libretro/retroarch-joypad-autoconfig#439]
I've received a new controller last week that had already the latest firmware installed. If you start Retroarch while the controller is connected it constantly sends control commands and breaks usage for me. Also my keyboard wasn't responsive anymore so I guess the mapping changed.

Downgrading to v1.23 fixed the problem for me but I think it's suitable to update the config files for autoconfig.

http://download.8bitdo.com/Firmware/Controller/SN30pro+SF30pro/SN30pro+SF30pro_Firmware_V1.25.zip

**Comment by Suspence00** [comment]
I can confirm, there is something really wonky going on.

So, on 1.25, with logs set to verbose, I initially see the controller come in with the PID:HID in Hex and Dec...but not the same as that of the configs .

Mine:
input_vendor_id = "1118"
input_product_id = "736"

Old:
input_vendor_id = "11720"
input_product_id = "24832"

I updated the values, restarted the controller and it synced, HOWEVER once you reload the screen, either via loading a game, changing the resolution, or closing and reopening retroarch, it unsyncs from the configs and get's registered as a new Xinput controller, with no button mapping.

Looking at the logs, after the restart, the controller is only showing the values in hex, not in dec. Which leads me to believe somewhere, somehow, after a reinitialization of the controllers it isn't converting the values to dec again. Or something, I'm really not sure.

Log Pic:
![image](https://user-images.githubusercontent.com/20601593/39657631-c958d9c0-4fd7-11e8-88cc-1a259298e22f.png)

**Comment by Suspence00** [comment]
Apparently setting the controller in D-input and having the Retroarch driver set to Xinput solved the problem for me on 1.25 fw
