### ISSUE TITLE
PS4 Legacy Controller Support Not Fully Functional

### ISSUE THREAD

**Issue by ghost** [libretro/retroarch-joypad-autoconfig#440]
So, about last month, my uncle got me this kit for making my own arcade stick. After completing the project, I went to go test it. The stick is fully functional on PC, but unfortunately it doesn't fully support the PS4. All of the buttons work fine on PS4, but the joystick itself doesn't function. If anybody can please figure out as to what's going on with it, that would be lovely. Thank you for taking your time to read this.
- Jonathan Ali

**Comment by RobLoach** [comment]
Feel free to export your config, and submit as a Pull Request. Thanks!
