### ISSUE TITLE
fix dragon rise settings between windows and linux

### ISSUE THREAD

**Issue by grant2258** [libretro/retroarch-joypad-autoconfig#453]
both controllers physical button numbers are identical under linux and windows layout wise

everything work as expected with auto mapping and all the auto binds match up they are all the same (xinput) in windows

linux the l and and r buttons are swapped.

when looking at the configs the only changes that are in the buttons is

(the physical is button  l=6 r=7 )

xinput (the one that works as expected)
input_l_btn = "6"
input_r_btn = "7"
input_l2_btn = "4"
input_r2_btn = "5"

udev
input_l_btn = "4"
input_r_btn = "5"
input_l2_btn = "6"
input_r2_btn = "7"

^^^^^^^^^
only works this way id you set it like this
input_l2_btn = "7"
input_r2_btn = "6"

if i change the xinput to the udev the behavior is identical the buttons swap

now im going under the assumption the number is the physical joystick button number i could be wrong. 

Shouldn't this just auto bind as l as l2 and r as r2  and have the same behavior because the button hasnt physically moved.  

I know the easy fix is just to change the udev to the xinput mapping. I just dont understand why the buttons are physically swapping when doing this can someone explain that?

**Comment by markwkidd** [comment]
@fr500 this has been quite vexing to figure out, so now that grant has finally figured out exactly how to reproduce the issue I hope you don't mind if I tag you

**Comment by markwkidd** [comment]
If I understand grants report fully @hunterk this seems more like an issue with the RetroArch input driver than from the autoconfiguration files. When you have time next, would you also consider checking to make sure that impression is true?

**Comment by grant2258** [comment]
this is probably a none issue i just looked at the source again i think the retropad is mapped differently ill close this for no think we are getting there now sorry about that ill explain when  i do more testing
