### ISSUE TITLE
Joypad config - Ipega PG-9068 Tomahawk [USB Mode]

### ISSUE THREAD

**Issue by iacques** [libretro/retroarch-joypad-autoconfig#475]
This is on usb mode... Please test in bluetooth mode too... Tks!

Save as "/storage/joypads/udev/Ipega_PG_9068_BT.cfg"

[Ipega_PG_9068_BT.cfg.txt](https://github.com/libretro/retroarch-joypad-autoconfig/files/2338951/Ipega_PG_9068_BT.cfg.txt)

input_driver = "udev"
input_device = "Ipega_PG_9068_BT"
input_device_display_name = "Ipega PG-9068 Tomahawk"
input_vendor_id = "9571"
input_product_id = "1571"
input_b_btn = "1"
input_y_btn = "4"
input_select_btn = "10"
input_start_btn = "10"
input_up_btn = "h0up"
input_down_btn = "h0down"
input_left_btn = "h0left"
input_right_btn = "h0right"
input_a_btn = "0"
input_x_btn = "3"
input_l_btn = "6"
input_r_btn = "7"
input_l2_btn = "8"
input_r2_btn = "9"
input_l3_btn = "13"
input_r3_btn = "14"
input_l_x_plus_axis = "+0"
input_l_x_minus_axis = "-0"
input_l_y_plus_axis = "+1"
input_l_y_minus_axis = "-1"
input_r_x_plus_axis = "+2"
input_r_x_minus_axis = "-2"
input_r_y_plus_axis = "+3"
input_r_y_minus_axis = "-3"

**Comment by snumryk** [comment]
What is this and how should i use this? (Ipega 9068 detects as keyboard on my PC, for some reasons)

**Comment by RobLoach** [comment]
Feel free to submit a Pull Request with the config! Also, mind adding some labels?
