### ISSUE TITLE
Detect a joypad with an analog stick

### ISSUE THREAD

**Issue by dekomote** [libretro/retroarch-joypad-autoconfig#484]
Not an issue per se, but I'm working on android mapping for some controllers, and I'm wondering if there's a way to tell retroarch that the joypad it's trying to autoconfigure is a pad with an analog stick. Is there such a flag in the autoconfigs?

**Comment by hizzlekizzle** [comment]
Not that I know of. What would the purpose be? To avoid false matches?

**Comment by dekomote** [comment]
The purpose would be to fully autoconfig the xbox controller from the get go, with analogs and all.

**Comment by hizzlekizzle** [comment]
Oh, I don't guess I understand, then. There are lots of pads with analogs:
https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/Sony-PlayStation3-DualShock3-Controller-Bluez.cfg#L21

**Comment by RobLoach** [comment]
Been some updates on xbox controllers. Feel free to re-test and re-open if this is still an issue.
