### ISSUE TITLE
G27 Wheel Ratio

### ISSUE THREAD

**Issue by Zewwy** [libretro/retroarch-joypad-autoconfig#496]
I'm hoping this is an easy issue to solve, but I can't seem to find any related information online about my problem.

I plug My G27 Wheel and I get the auto-config pop up notification stating G27 Wheel is configured on Port 1. Which is all fine, and I can assign the device to Player 1.

However I can't seem to adjust the axis end points... it's defaulting to 900 degrees of rotation.... It's extremely difficult to play racing games with steering like a semi truck... by the time I get my wheel turned I'm half way into the turn and going out of bounds... haha

Please help!

**Comment by hizzlekizzle** [comment]
I'm afraid we don't have any way of dealing with that, though I agree that we probably should.

**Comment by Zewwy** [comment]
Not exactly what I wanted to hear hahaha, got so close to finishing this cabinet... this is literally like the final hurdle.. :(

**Comment by hizzlekizzle** [comment]
Can you do any calibration in your OS/driver?

**Comment by Zewwy** [comment]
Already made a post there; Lakka...

https://forums.libretro.com/t/g27-wheel-causes-ui-control-issues/20042/3

**Comment by Zewwy** [comment]
Not sure as for driver, figured this was as close as I could get...

**Comment by RobLoach** [comment]
Been two years since this was opened. Going to close it, but feel free to re-open with some additional information if you're still running into it.
