### ISSUE TITLE
[macOS] SLS Sega Saturn USB gamepad not found

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/retroarch-joypad-autoconfig#509]
Workaround:

Copy
`autoconfig/udev/SLS-Sega-Saturn-USB-Gamepad.cfg`
to
`autoconfig/hid/SLS-Sega-Saturn-USB-Gamepad.cfg`

Which makes me wonder why there are some controller configurations in `udev` for Linux that are not in `hid` for other platforms?

**Comment by gingerbeardman** [comment]
That would be an idea.

Another example, compare these:
https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/android/8Bitdo_Pro_SF30_USB.cfg
https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/hid/8Bitdo_Pro_SF30_USB.cfg
https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/8Bitdo_Pro_SF30_USB.cfg

**Comment by gingerbeardman** [comment]
Just had to redo this cfg for xinput!

Will do a PR soon.

**Comment by offalynne** [comment]
I think hizzle meant to inquire whether the button/axes values are always enumerated the same way between each platform’s drivers, which they sometimes are, but this is certainly not always the case. Configs shouldn’t be copied unless you can confirm yourself the results work correctly.

**Comment by gingerbeardman** [comment]
Oh, hi. Yes, of course I understood exactly that. 

In my experience between udev, hid and xinput the buttons for the same controller (ie. the ones I have here now) enumerate identically across all three platforms. See the 8-bit do above, and the SLS PR will come soon.

That said, is it likely that this repo will be reorganised to pool those three platforms and benefit their users?

**Comment by offalynne** [comment]
While a few will work out the same, they often do differ between drivers. You're right that 8BitDo maps are usually the same, though that too depends on the startup mode.

>  is it likely that this repo will be reorganised to pool those three platforms

No

**Comment by hizzlekizzle** [comment]
It would be awesome if they could all be combined, but if it's not reliable, it can't happen. :(

**Comment by gingerbeardman** [comment]
Why is it not reliable?

**Comment by hizzlekizzle** [comment]
> While a few will work out the same, they often do differ between drivers. Even the name field can give different results.
