### ISSUE TITLE
Config missing for 8bitdo N30 NS, Bluetooth controller for Nintendo Switch

### ISSUE THREAD

**Issue by ptwiv** [libretro/retroarch-joypad-autoconfig#513]
I got two of the newer 8bitdo N30 for NS bluetooth controllers, and the default button mappings are not correct.  Both A and B button are mapped to the same button, the shoulder buttons don't work, and the turbo A & B buttons aren't working.  Can someone add a config for this controller, or provide some guidance that I can follow to map the config?

**Comment by hizzlekizzle** [comment]
which driver are you using?

**Comment by ptwiv** [comment]
Joypad driver is xinput, and I am using Retroarch on a Windows 10 PC.  

Let me add that I have no troubles with SF30 Pro and SN30 Pro controllers, nor PS3 or PS4 controllers.

**Comment by hizzlekizzle** [comment]
Hmm, it looks like the only one that's mapped strangely is the modkit. Can you try deleting that config and see if it starts treating you better? It's this one:
https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/xinput/8Bitdo_N30_Modkit_BT.cfg

**Comment by ptwiv** [comment]
I removed that config file and still encountered the same issues.

I had time tonight to dig into the actual issue, and in Retroarch, under Input settings, the User1 Device Input is mapped to SwitchProController by default when the controller is enabled.  Just to clarify, I am using this controller specifically: http://www.8bitdo.com/N30-NS/ http://download.8bitdo.com/Manual/Controller/N30-NS/N30-NS.pdf

With the current setup, the button layout is as follows:
A button is mapped to Turbo A
B button is mapped to A
Both Turbo A and B are mapped to Turbo A
Start and Select are not mapped to any buttons
ZL (Left Bumper) Start
ZR (Right Bumper) Select

**Comment by hizzlekizzle** [comment]
ok, I think I know what's up: I believe the gamepad is masquerading as a Switch Pro Controller (that is, it's announcing its vid/pid as those of the Switch Pro Controller) to make it compatible with the Switch. Most 8bitdo pads have several different pairing modes you can use for compatibility. Can you see if there's a xinput/dinput mode you can pair with when you're on PC?

**Comment by ptwiv** [comment]
I have emailed 8bitdo support for guidance, they're saying this is only for the Switch at the moment.  I'll have to debate on whether to try and return, or to wait and see if they eventually release a firmware update that allows this to be used properly on a PC.

**Comment by RobLoach** [comment]
Been some updates on here. Make sure to update your firmware from the 8bitdo website.
