### ISSUE TITLE
Configuration for 8Bitdo M30 bluetooth for Android

### ISSUE THREAD

**Issue by djfjeff** [libretro/retroarch-joypad-autoconfig#518]
Hi,

8Bitdo just released the new M30 bluetooth and I was trying to use it on my Shield TV. However, Retroarch does not detect it correctly and fallback.

I could not find another profile that seems to match it (6 faces buttons + 2 shoulders buttons).

Is there any plan to add an autoconfig profile for it?

Thanks,

**Comment by hizzlekizzle** [comment]
For autoconfig profiles, we can't possibly own every controller, so we rely on user submissions. It should be mapped like this:
LXR
YBA
with the shoulder buttons mapped to the retropad's triggers.

**Comment by djfjeff** [comment]
Thanks, I have opened a pull request with the autoconfig I made : https://github.com/libretro/retroarch-joypad-autoconfig/pull/519
