### ISSUE TITLE
Archos Gamepad and Ouya Controller

### ISSUE THREAD

**Issue by Quickgold74** [libretro/retroarch-joypad-autoconfig#52]
In Archos Gamepad the autoconfig function it doesn't works with the analogs as well if you try to bind manually the analogs sticks, both sticks are in the autoconfig file and when you try to bind manually RA doesn't recognize them (The Analogs Sticks works fine with other emulators like Nes.Emu, Snes9x EX+, PPSSPP, ePSXe)

With OUYA fails the back button, it works but is random (maybe works or not) in RA 1.0.0.2 from Play Store the back button works fine.

Please improve the Hardware detection. Thanks!

**Comment by fr500** [comment]
We need new feedback on this, if you're willing to help us improve, reopen
