### ISSUE TITLE
defender game master gamepad

### ISSUE THREAD

**Issue by zeroloket** [libretro/retroarch-joypad-autoconfig#57]
input_device = "ShanWan USB WirelessGamepad "
input_driver = "udev"
input_b_btn = "2"
input_y_btn = "3"
input_select_btn = "8"
input_start_btn = "9"
input_up_axis = "-1"
input_down_axis = "+1"
input_left_axis = "-0"
input_right_axis = "+0"
input_a_btn = "1"
input_x_btn = "0"
input_l_btn = "4"
input_r_btn = "5"
input_l2_btn = "6"
input_r2_btn = "7"
input_l3_btn = "10"
input_r3_btn = "11"
input_l_x_plus_axis = "+0"
input_l_x_minus_axis = "-0"
input_l_y_plus_axis = "+1"
input_l_y_minus_axis = "-1"
input_r_x_plus_btn = "1"
input_r_x_minus_btn = "3"
input_r_y_plus_btn = "2"
input_r_y_minus_btn = "0"
input_vedor_id = 9571
input_device = "ShanWan USB WirelessGamepad "
input_driver = "udev"
input_b_btn = "2"
input_y_btn = "3"
input_select_btn = "8"
input_start_btn = "9"
input_up_axis = "-1"
input_down_axis = "+1"
input_left_axis = "-0"
input_right_axis = "+0"
input_a_btn = "1"
input_x_btn = "0"
input_l_btn = "4"
input_r_btn = "5"
input_l2_btn = "6"
input_r2_btn = "7"
input_l3_btn = "10"
input_r3_btn = "11"
input_l_x_plus_axis = "+0"
input_product_id = 1351

**Comment by hizzlekizzle** [comment]
Should this be:
input_device = "ShanWan USB WirelessGamepad "
input_driver = "udev"
input_b_btn = "2"
input_y_btn = "3"
input_select_btn = "8"
input_start_btn = "9"
input_up_axis = "-1"
input_down_axis = "+1"
input_left_axis = "-0"
input_right_axis = "+0"
input_a_btn = "1"
input_x_btn = "0"
input_l_btn = "4"
input_r_btn = "5"
input_l2_btn = "6"
input_r2_btn = "7"
input_l3_btn = "10"
input_r3_btn = "11"
input_l_x_plus_axis = "+0"
input_l_x_minus_axis = "-0"
input_l_y_plus_axis = "+1"
input_l_y_minus_axis = "-1"
input_r_x_plus_btn = "1"
input_r_x_minus_btn = "3"
input_r_y_plus_btn = "2"
input_r_y_minus_btn = "0"
input_vendor_id = 9571
input_product_id = 1351
[removed redundant entries and changed "vedor" to "vendor"]

**Comment by zeroloket** [comment]
lok, yes that is right

**Comment by zeroloket** [comment]
Lol

**Comment by hizzlekizzle** [comment]
Ok, got it added. Let us know if it doesn't work as expected.
