### ISSUE TITLE
Add labels to configurations where missing

### ISSUE THREAD

**Issue by offalynne** [libretro/retroarch-joypad-autoconfig#572]
As discussed in @MatiasFernandez's recent work in the repo, [roughly one](https://github.com/libretro/retroarch-joypad-autoconfig/search?p=11&q=%22input_driver%22+NOT+%22_label%22) out of [every five configs](https://github.com/libretro/retroarch-joypad-autoconfig/search?q=%22input_driver%22&unscoped_q=%22input_driver%22) is currently missing labels, whether they pre-date the implementation or were contributed without them. This is obviously a significant undertaking, and guesswork should presumably be discouraged, but for well-known devices or recent PRs where the contributor is communicative and willing to update their configs, it seems like a worthwhile effort to undertake.

I'll have a look at what I've got on hand in a little while and see if I can contribute anything to this end.

**Comment by mrestifo** [comment]
I might be able to assist in this effort as well.

**Comment by hizzlekizzle** [comment]
@mrestifo sure, that'd be great :)

**Comment by RobLoach** [comment]
Feel free to submit any changes through Pull Requests!
