### ISSUE TITLE
How to create autoconfig for new gamepad (iPega PG-9083S)

### ISSUE THREAD

**Issue by guoyunhe** [libretro/retroarch-joypad-autoconfig#599]
I got this new gamepad today (iPega PG-9083S). I installed RetroArch on Android and connect to the controller. But I cannot configure it through User 1 Binds menu. Cannot save autoconfig (unknown error).

How could I make an autoconfig for it?

**Comment by guoyunhe** [comment]
I found it has a mode switch: the "gamepad" icon is the correct mode. It is recognized as PG-9055 BT but works fine.

**Comment by RobLoach** [comment]
Your config was merged! Thanks a lot :wink:
