### ISSUE TITLE
Add autoconfig file for iNNES SNES gamepad

### ISSUE THREAD

**Issue by LehighBri** [libretro/retroarch-joypad-autoconfig#600]
Hi there - I wasn't sure how to do a pull request, so I wanted to add my autoconfig for a new controller that wasn't detected.  Can you please add?  It's attached and below

input_driver = "udev"
input_device = "iNNEXT SNES Gamepad"
input_vendor_id = "121"
input_product_id = "294"
input_b_btn = "2"
input_y_btn = "3"
input_select_btn = "8"
input_start_btn = "9"
input_up_axis = "-1"
input_down_axis = "+1"
input_left_axis = "-0"
input_right_axis = "+0"
input_a_btn = "1"
input_x_btn = "0"
input_l_btn = "4"
input_r_btn = "5"

[iNNEXT SNES Gamepad.zip](https://github.com/libretro/retroarch-joypad-autoconfig/files/3923551/iNNEXT.SNES.Gamepad.zip)

**Comment by hizzlekizzle** [comment]
Sure, added it for you. Thanks!

https://github.com/libretro/retroarch-joypad-autoconfig/commit/b48afbc3dad042bbb5549605618b393d695f5734
