### ISSUE TITLE
trying to submit pull request- noob

### ISSUE THREAD

**Issue by dmitchell1981** [libretro/retroarch-joypad-autoconfig#602]
I am trying to submit the cfg file for a Tomee NES to USB Controller Adapter
input_driver = "udev"
input_device = " NES PC Game Pad     NES PC Game Pad   "
input_vendor_id = "7511"
input_product_id = "33"
input_b_btn = "1"
input_start_btn = "3"
input_up_axis = "-1"
input_down_axis = "+1"
input_left_axis = "-0"
input_right_axis = "+0"
input_a_btn = "0"

**Comment by hizzlekizzle** [comment]
Got it, thanks!

https://github.com/libretro/retroarch-joypad-autoconfig/commit/2ec2f7fd753798a19202fbdebe51948ecd9fb2d5
