### ISSUE TITLE
Dualshock 4 v2 issues

### ISSUE THREAD

**Issue by ZackXu0** [libretro/retroarch-joypad-autoconfig#621]
> Device: macOS 10.15.3 + RetroArch 1.8.4 (not Metal version) + Dualshock 4 v2 (Model CUH-ZCT2G)

It seems to be considered as having 2 controllers connected, using on my device will control both player 1 and player 2.

I'm not sure if this problem exists because Apple added something after updating the system to support Apple Arcade, please help me.

Thanks!

**Comment by hizzlekizzle** [comment]
Usually, you just need to go into settings > input > port 2 binds and change the device index for p2 away from it.

**Comment by ZackXu0** [comment]
I only connected one dualshock 4 controller and it thought I connected 2

https://www.dropbox.com/s/92gguwhbwggck2z/Dualshock4.png

**Comment by RobLoach** [comment]
Dup? https://github.com/libretro/retroarch-joypad-autoconfig/issues/622
