### ISSUE TITLE
SNES Switch Online controller on macOS not being configured …

### ISSUE THREAD

**Issue by fooness** [libretro/retroarch-joypad-autoconfig#625]
Hello everyone.

I just wanted to try my new SNES Switch Online controller with RetroArch, but it seems there’s some problems with the autoconfig (or even manual config). Thanks to @Dr-Ocelot, there’s already an autoconfig configuration for this controller. It’s located in the `xinput` directory and can be found via [this link](https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/xinput/SNES_Nintendo_Switch_Online.cfg) in the libretro repository.

The autoconfig file looks perfectly fine, but it doesn’t work out of the box. What does work, though, is copying the `xinput/SNES_Nintendo_Switch_Online.cfg` file to the `hid` directory, i.e. `hid/SNES_Nintendo_Switch_Online.cfg` …

Any idea what might be the problem here? I DID NOT change the `input_driver` in the autoconfig file, I just copied it to the `hid` directory.

(FYI: I DID TRY to change the `input_driver` to `hid` during my tests, the controller even worked in RetroArch, but no keybindings where shown in the input settings.)

—

macOS: 10.14.6
RetroArch: 1.8.4

**Comment by Dr-Ocelot** [comment]
I believe this is because macOS might not support xinput.

**Comment by fooness** [comment]
But … the `xinput` configuration works perfectly fine by just copying to the `hid` directory.
That’s weird, isn’t it?

**Comment by offalynne** [comment]
not really. some, but not all devices happen to map the same way.

**Comment by RobLoach** [comment]
If you made changes to the autoconfig and they worked, please submit those changes as a Pull Request so that they stick. Thanks!

**Comment by gouchi** [comment]
@fooness Please close this issue as the autoconfigs have been added by this [commit](https://github.com/libretro/retroarch-joypad-autoconfig/pull/1101).

Thank you.
