### ISSUE TITLE
Turn ON the ANALOG light to get the right config

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/retroarch-joypad-autoconfig#63]
Just a note, must be somewhere in the wiki: users need to turn the ANALOG light ON in these generic PS2/PS3 joypads to get the right config, otherwise they will get the same value to D-pad and left analog axis, for example, which is not valid (at least for RA).

So each button in the joypad MUST have different values.

![generic ps3 joypad](https://cloud.githubusercontent.com/assets/5431285/8609913/dd8ce3dc-2681-11e5-9278-d99c95e16680.png)

Take a look at @f995bd1

**Comment by sergiobenrocha2** [comment]
f2c2264

**Comment by sergiobenrocha2** [comment]
@magwe 

```
Corrected mapping of right analog stick
```

in f2c2264, my joypad is wrong.

What's the "right" joypad, mine or yours?

**Comment by magwe** [comment]
@sergiobenrocha2 I think it is probably a matter of who has the right driver. I mentioned this in the comments of the .cfg file.

```
+# Note that the linux kernel driver for this controller was broken from
+# kernel 4.4 until 4.9. With the broken driver the joystick axes
+# numbers will be off. This can be fixed by reverting commit
+# 18339f59c3a6698ee17d32970c9e1e450b16e7c3 and rebuilding hid-dr.ko.

```

Are you using the stock driver from linux 4.4+ ? If so It is broken. The fix isn't merged in mainline stable yet. (it is in the 4.9-rc commits though..)

**Comment by sergiobenrocha2** [comment]
I'm using 3.13.0-100-generic from ubuntu 14.04

**Comment by magwe** [comment]
OK, then my best guess is that you have the gamepad that caused the kernel regression in the first place. In that case, to fix you specific gamepad you need this additional kernel commit (also in kernel 4.9):

https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/drivers/hid/hid-dr.c?id=e15944099870f374ca7efc62f98cf23ba272ef43

**Comment by RobLoach** [comment]
Closing this for now. Feel free to re-open if it's still an issue.
