### ISSUE TITLE
vid/pid format fix

### ISSUE THREAD

**Issue by offalynne** [libretro/retroarch-joypad-autoconfig#631]
https://github.com/libretro/retroarch-joypad-autoconfig/blob/0ebca0c491992dbbcdb5f960e261236c547b0ba3/udev/Jess_Tech_Colour_Rumble_Pad.cfg

https://github.com/libretro/retroarch-joypad-autoconfig/blob/0ebca0c491992dbbcdb5f960e261236c547b0ba3/udev/XEOXPro.cfg

ids in these map are hex instead of dec. unable to PR rn so leaving note for posterity.

**Comment by hizzlekizzle** [comment]
Got 'em. Thanks for the heads-up!
