### ISSUE TITLE
[UBUNTU]Slow loading/closing times when using bluetooth 8bitdo controller

### ISSUE THREAD

**Issue by Mangus78** [libretro/retroarch-joypad-autoconfig#632]
Since 1.8.5 I again have this strange behavior with mi sf30 pro 8bitdo bluetooth controller:
every time I launch a game (or closing it), or every time I load a saved state, or update system files (like cores), on retroarch, I encounter some very long waiting times.
I had the same problem months ago and fixed it choosing a different input driver. It doesn't work anymore after 1.8.5 update.
No problems whatsoever if I use the same controller with usb cable or using xbox 360 controller.

**Comment by goodjaerb** [comment]
Same issue I believe being tracked on retroarch https://github.com/libretro/RetroArch/issues/10408. Something to do with bluetooth and possibly the battery indicator.

**Comment by Mangus78** [comment]
I've noticed that turning OFF "show battery level" under settings>user interface>views, resolved the issue and now there are no more lag or dalay doing whatsoever. So it seems to be definitely a battery check issue.

**Comment by RobLoach** [comment]
See the issue linked above. Thanks!
