### ISSUE TITLE
DualShock 4 autoconfig problem on android

### ISSUE THREAD

**Issue by klepp0906** [libretro/retroarch-joypad-autoconfig#642]
Fortunately I have two Nvidia shields so was able to track this down with relative ease. 

Connected my ds4 via usb to one and fully updated.  Suddenly I couldn’t enter the menu from games which I had bound to start+select. 

I tracked it down to being the “select” half of the equation. 

After testing on the other shield which I could enter the menu I updated everything BUT the autoconfig.  Could still enter the menu. 

Updated autoconfig, poof - issue. Fortunately I backed up the older one so I’m not screwed,  but figured I’d better mention it so I don’t have to refrain from updating AND remember to hold the old autoconfigs perpetually lol.

**Comment by klepp0906** [comment]
K - just dove into the files and found it pretty easily

`Sony_Dualshock_4_Controller_USB.cfg` in the android folder has `input_select_btn = "4"` in the working version and `input_select_btn = "109"` in the non working version.

no idea why the change, other than the fact that you would "expect" the select button to be 108 considering start is 109.  Via testing that simply isnt the case.

mapped it manually and checked the resulting cfg myself. 

manually changed via a text editor on the other shield and it began working again etc.

**Comment by RobLoach** [comment]
A few changes were merged forwards. Thanks!
