### ISSUE TITLE
The gamepad does not work.

### ISSUE THREAD

**Issue by alexb3d** [libretro/retroarch-joypad-autoconfig#643]
It does not recognize the Xbox 360 controller. The Jstest program recognizes it perfectly.
I have RetroArch installed with Flatpak on Ubuntu 20.04.

**Comment by hizzlekizzle** [comment]
this is probably a flatpak-specific issue.

**Comment by alexb3d** [comment]
Sure, there are so many sites to report a bug that is very confusing.

**Comment by RobLoach** [comment]
It's confusing having >1400 uncategories issues in one place. Issues with RetroArch on Flatpak go on the Flatpak repo.

**Comment by alexb3d** [comment]
I understand it can be confusing, I try to do the best I can, but how can I know that the error is from flatpak and not from retroarch? I am not a programmer and I saw your message late.
