### ISSUE TITLE
8BitDo face button order confirmation

### ISSUE THREAD

**Issue by offalynne** [libretro/retroarch-joypad-autoconfig#659]
Most of the older 8BitDo configs indicate they were authored with older firmware that no longer match the same button layout mappings. Anyone with 8BitDo pads is encouraged to update their device and check if the appropriate configs need updating.

(Made note in the PR for the modkits: https://github.com/libretro/retroarch-joypad-autoconfig/commit/32a8ed2523cd9f6b42acf2196ff3897a12b70a3d#commitcomment-40246673)

**Comment by RobLoach** [comment]
Thanks a lot!
