### ISSUE TITLE
360(and clones) guide button can't be unbound. it is locked as auto and menu toggle

### ISSUE THREAD

**Issue by medievil1** [libretro/retroarch-joypad-autoconfig#676]
delete or space do not clear it

**Comment by bslenul** [comment]
Yeah, Space resets to default value (the one from your autoconfig file) and Delete can't delete autoconfig binds :/ 

So you'd have to open the autoconfig with a text editor and either delete the `input_menu_toggle_btn` line or comment it by adding `#` at the very beginning of the line (`#input_menu_toggle_btn = "10"` for example).

**Comment by sonninnos** [comment]
`input_menu_toggle_btn = "nul"` works fine too.

**Comment by Sanaki** [comment]
Since nothing is wrong with the actual autoconfig, this issue should be closed. If you want the ability to bind an empty value to override autoconfs (which seems a reasonable request), that request should be opened in https://github.com/libretro/RetroArch/.

**Comment by medievil1** [comment]
sorry yea, should have closed this a while back, it was resolved
