### ISSUE TITLE
CHA2.cfg is missing select button config

### ISSUE THREAD

**Issue by cjom** [libretro/retroarch-joypad-autoconfig#690]
There is a line missing in CHA2.cfg:

input_select_btn = "7"

Also, I can't figure if there is a configuration file for CHA1... the only difference from CHA2 is input_product_id = "36".

**Comment by offalynne** [comment]
Where is the "Select" button on the stick and what is it labeled? Can't find a photo of the product that shows it.

**Comment by cjom** [comment]
The photos from top view are not very clear because the buttons colors blend in Capcom logo. I hope this picture is clear enough.
![CHA](https://user-images.githubusercontent.com/55603581/93338074-7809cb00-f819-11ea-81d3-74ea83396456.jpg)


Saving the config from RetroArch (Lakka 3.0) it creates the attached files.

# CHA1.cfg
```
input_driver = "udev"
input_device = " CHA1     CHA1   "
input_vendor_id = "7258"
input_product_id = "36"
input_b_btn = "3"
input_y_btn = "0"
input_select_btn = "7"
input_start_btn = "6"
input_up_axis = "-1"
input_down_axis = "+1"
input_left_axis = "-0"
input_right_axis = "+0"
input_a_btn = "4"
input_x_btn = "1"
input_l_btn = "2"
input_r_btn = "5"
```

# CHA2.cfg
```
input_driver = "udev"
input_device = " CHA2     CHA2   "
input_vendor_id = "7259"
input_product_id = "37"
input_b_btn = "3"
input_y_btn = "0"
input_select_btn = "7"
input_start_btn = "6"
input_up_axis = "-1"
input_down_axis = "+1"
input_left_axis = "-0"
input_right_axis = "+0"
input_a_btn = "4"
input_x_btn = "1"
input_l_btn = "2"
input_r_btn = "5"
```

**Comment by gouchi** [comment]
@cjom This issue should be closed as it has both [CHA1.cfg](https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/CHA1.cfg)  and  [CHA2.cfg](https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/CHA2.cfg) have been updated.

Thank you.

**Comment by cjom** [comment]
OK, thanks.

**Comment by gouchi** [comment]
@cjom Don't forget to close this issue ;) Thank you.
