### ISSUE TITLE
Please help to crack

### ISSUE THREAD

**Issue by commy0721** [libretro/retroarch-joypad-autoconfig#699]
I am a very old game console with its bios file! The purpose of Super Nintendo’s Doctor 7 drive is to connect to a serial external optical drive on the market! I have tried to connect the machine to display and the computer is successfully connected! This machine can also be connected to its original serial optical disc drive, but it is difficult to find such a machine on the market! There are also more than 2,000 to more than 3,000 expensive. Because the machine has been around for nearly 30 years, I want to crack the games that must be stored on the optical disc when connected to the external optical drive. A game requires a palm disk or even 56 disks, so I want to crack the bios! I use UltraEdit to open the extracted bios file, it is garbled and can’t read, so please help. Thank you! I also want to learn from the great gods! Thank you very much! The following is a link to the bios file 
    
https://pan.baidu.com/s/1Yplx-BDBUJkhZr9DLFns7A    Extraction code：9ur6

**Comment by RobLoach** [comment]
Naw.
