### ISSUE TITLE
Suggestion/Issue? RetroPad Config Not Found/Working

### ISSUE THREAD

**Issue by hardknoxni69a** [libretro/retroarch-joypad-autoconfig#720]
So apparently the official documentation is wrong or no one i have spoken to knows so they just said its not possible but anyway... It would be very convenient for users who have multiple controllers to be able to map the hotkeys to the retropad rather than phsyical buttons. Say I have my retropad start button programmed to button 7(physical start button) then I program a hotkey to "RetroPad Start" this way the hotkey will use automatically consider the start button as the hotkey. This will be so much simpler for users with multiple controllers. Instead of programming each individual controller no matter if its button 6 or 9 or 0 wont matter whatever button you mapped as start will automatically be considered the hotkey. This seems like such an efficient way to mapping hotkeys. Mapping 10 controller's hotkey will be a breeze for everyone and especially easier for the family we could just say the start button is the hotkey for every controller instead of well when your using the Nintendo controllee its select but when your using the sega controller mode button and if your using the Xbox controller it's guide oh ya and it's the PS button on the Playstation controller oh ya don't forget there's no mode or select or Xbox button on the n64 controller so it's the z button lol. As you can imagine it can get complicated with many controller's. My thoughts are the most basic of hotkey uses that people use are exit, menu, load, save, +save slot, -save slot. So want to set start as hotkey, a as menu, b as exit, down as save, up as load, left as -save slot, right as +save slot for every single controller. As those buttons are basically on every controller from NES and above. That's why I think having those basic functions programmed that way would be easiest for the family. So yes if there is a way to program to retropad values in the future this would be amazing 

Original issue below.
So after digging around there is many references to "RetroPad Select" RetroPad L1" "RetroPad A" Etc. You get the idea. Well we are supposed to have the option to link hotkey to RetroPad buttons. Such As

Input_enable_hotkey = "RETRO_DEVICE_ID_JOYPAD_START"
Input_menu_toggle = "RETRO_DEVICE_ID_JOYPAD_A"
Input_exit_emulator = "RetroPad B"
Input_save_state = "RetroPad Down"
Input_load_state = "RetroPad Up"
Input_state_slot_increase = "RetroPad Right"
Input_state_slot_decrease = "RetroPad Left"

I am try to figure this out so it will make programming the hotkeys for over 22+ controllers just a little easier. The official documents say "Tip! Hotkeys Can Be Mapped To RetroPad Buttons." This tip unfortunately does not explain the names that retroarch looks for to recognize the retropad settings. Based on each controller the hotkey values are different so for 1 controller the button that represents B might be "2" but it would be "7" on the next controller and "4" on the other controller. Well I have over 22 controllers thst will need programming so I decided it would be the perfect time to follow the guide and actually map the "RetroPad" that way instead of looking for button "1" to toggle menu it will be looking for "RetroPad A" That way whichever controller I am using the button that has been mapped to "RetroPad A" will be recognized as the hotkey. Doing in this manner will make things just a littler smoother when it comes to multiple controllers. So 2 issues the docs do not mention the code that retroarch is looking for to represent "RetroPad A" It could be just that "RetroPad A" or I also seen in some code "RETRO_DEVICE_ID_JOYPAD_A" so my friends what string represent "RetroPad A" also there is multiple input calls for a hotkey such as

Input_menu_toggle
Input_menu_toggle_axis
Input_menu_toggle_btn
Input_menu_toggle_mbtn

SO the million $ question is what is the string that will toggle the menu and make it use RetroPad A as the value? Sorry for the book but I just know if I am not clear It won't make sense.
So what's the total string to make the toggle menu work using any button as long as it is mapped to the "RetroPad A". And will I need to nul out any other button values as I know there are some cfg that take precedence. So thanks for your help I am sure one of you who actual work on this code daily will be like hey its this simple. I apologize for bothering but I have searched for a week now trying to find the answer so I figured it is time to ask the people who pump the blood into retroarch. Thank You ALL so much for all the work you have put into this.

**Comment by RobLoach** [comment]
Capture the button, export the config, and then you'll see if in the file system. Submit the changes up through a Pull Request and we'll get them merged. thanks.

**Comment by hardknoxni69a** [comment]
I am not sure what you are asking of me. Are you referring to the hotkeys being those that I mentioned? You want me to Program the hotkeys like I stated and upload that file?

**Comment by hardknoxni69a** [comment]
My idea is to have the main settings hotkeys be programmed to the retropad values instead of button #s. Currently we go into menu>settings>input>player1> then we bind all the retropad to button #s. Then we can go into input>hotkeys and edit the hotkeys and set to buttons #s too. So instead of binding hotkeys to button #s. We will bind them to the retropad values. For example instead of choosing saveslot_btn = 7 we will choose saveslot_btn = D-Pad-Down. Retroarch will automatically determine that D-Pad-Down= 7 because that is how we binded it in player controls. This way no matter what controller we are using it will just look in player binds and adjust to that controller. Every controller is different so instead of adjusting hotkeys per controller we will have the option to bind to retropad value.

**Comment by RobLoach** [comment]
That would be pretty cool. There's a few hot-combo bindings been made. Would love to see more.
