### ISSUE TITLE
Not detecting Xbox Wireless Controller properly via Bluetooth

### ISSUE THREAD

**Issue by tomcres** [libretro/retroarch-joypad-autoconfig#730]
My Retroarch was working fine with my Xbox Wireless Controller (via Bluetooth) until last night when I did "update controller profiles" and then "update assets" from the Online Updater. Then Retroarch restarted and now detects my controller as an "8bitDo N30 ModKit." This is a standard Microsoft Xbox Wireless Controller (the newer ones for the Xbox One that have built-in Bluetooth capability). It's a very common controller, so this seems to be a mistake. Have not been able to figure out how to override it either.

**Comment by ToniBC** [comment]
Something similar happens to me, almost all of the xinput profiles were deleted, now there are only a few and when I connect my 8bitdo SF30 PRO controller via BT, it detects it as 8bitDo N30 ModKit and before it detected it as an Xbox One controller.

It is not auto-configured either and although I configure it by hand, it seems that it does not work completely correct. Observe that the analog mixes or interferes with the digital crosshead, makes like incorrect keystrokes.

I solved it by putting the autoconfig of the standalone version 1.9.0, but you would have to see what happened with the rest of the profiles.

The funny thing is also that, if I connect the remote control by cable, it recognizes it there without problems, but what I say happens through BT.

**Comment by 6lackmag3** [comment]
Autoconfig for XBox One conflicts with recently added autoconfig for 8bitdo N30 ModKit due to same pid and vid in both files.
@RobLoach can you fix it please? https://github.com/libretro/retroarch-joypad-autoconfig/commit/9669cd494814fce90231080f55da5dcaf82dd830

**Comment by offalynne** [comment]
Must be a missing or bad name on the appropriate Xbox One profile, should be fixable by commenting out vid/pid on the config in question. Which OS?

**Comment by 6lackmag3** [comment]
Window 10 x64.
XBox One gamepad detected correctly if 8Bitdo l_N30_ModKit.cfg is moved from autoconfig/xinput. It also detected correctly on stable 1.9.0 as been mentioned earlier.

**Comment by offalynne** [comment]
Yeah, would suggest just making the `input_vendor_id` and `input_product_id` line comments (start line with #).

**Comment by Sanaki** [comment]
This can be closed. I resolved it in #738.
