### ISSUE TITLE
Xbox one S bluetooth android autoconfig issues

### ISSUE THREAD

**Issue by Honest-n** [libretro/retroarch-joypad-autoconfig#739]
In the android/Xbox One S Wireless Controller.cfg file the View/select button on an xbox one s controller has an incorrect button value of 4 when it should read 109, I have submitted a pull request

**Comment by RobLoach** [comment]
I don't see the pull request?

**Comment by Honest-n** [comment]
Already been merged....

**Comment by RobLoach** [comment]
Thanks!
