### ISSUE TITLE
[Discussion] Move disabled/non-working profiles into subdirectories?

### ISSUE THREAD

**Issue by Sanaki** [libretro/retroarch-joypad-autoconfig#742]
I brought this up on discord and was asked to open an issue. 

Currently 150 autoconfs are non-functional. Of these, 126 don't have a vendor ID listed at all, which makes them unloadable. Another 24 have it listed but disabled due to conflicts with other more prominent profiles. I'd like to move these into a subdirectory named "inactive", "non-working", or something else similar to give a clearer view of which functional autoconfs we have and which we don't, to help simplify matters for people who work on improving this repo.

In case anyone on Linux wants to see the list:
`find . -iname "*.cfg" -exec grep -LE "^input_vendor_id" "{}" \;`
And for ones that are explicitly disabled:
`find . -iname "*.cfg" -exec grep -lP "^[#\s]+input_vendor_id" "{}" \;`

**Comment by offalynne** [comment]
Name match doesn't require Vendor ID.

**Comment by Sanaki** [comment]
This is news to me. I was under the impression autoconfs couldn't be loaded without at minimum vid:pid present. I do know name match seems to be useless when they -are- present, so it makes some sense. I'll have to test that out.

**Comment by Sanaki** [comment]
Confirmed that behavior. Grand total of four left. Not sure how much it matters at that point. Command used:
`find . -iname "*.cfg" -exec grep -LE "^input_vendor_id" "{}" \; | xargs -d "\n" grep -LE "^input_device"`

Results, all intentionally disabled:
./udev/HuiJia  USB GamePad.cfg
./udev/USB_Gamepad_.cfg
./android/Defender_Game_Racer_Classic.cfg
./android/GPD_Q9.cfg
