### ISSUE TITLE
Sony 'Dual Shock 4 V2' and '500 Million Limited Edition' have the same Vendor and Product ID but different button layout.

### ISSUE THREAD

**Issue by radmedres** [libretro/retroarch-joypad-autoconfig#749]
Hi,

I have three Dual Shocks V2 and when I download the autoconfig I have to manual delete Sony_PlayStation4_Dualshock4_500-Million_Limited_Edition.cfg to get my Sony-PlayStation4-DualShock4v2-Controller to work correctly.
They both have the same Vendor and Product Identification, but different button layouts in the configuration. 
For me, it shows immediately because the Circle and Cross have swapped when I leave Sony_PlayStation4_Dualshock4_500-Million_Limited_Edition.cfg in the autoconfig folder.

**Comment by uli42** [comment]
looks similar to my #760: the input_device string of the two config files is not honored

**Comment by RobLoach** [comment]
Change was merged! Feel free to create a new issue if it's still missing.
