### ISSUE TITLE
[Request] Support for 8bitDo Arcade Stick (80FE)

### ISSUE THREAD

**Issue by Rstation4** [libretro/retroarch-joypad-autoconfig#752]
https://www.8bitdo.com/arcade-stick/

It has the ability to upgrade the firmware.

**Comment by offalynne** [comment]
https://github.com/libretro/retroarch-joypad-autoconfig#how-to-create-an-autoconfig-file

https://www.retroarch.com/index.php?page=joypad-autoconfig

**Comment by hizzlekizzle** [comment]
Right, someone who owns (or has access to) the device would need to make and submit a profile for it.

**Comment by Rstation4** [comment]
Do you use some kind of software to get the input info from these devices? Im no programmer so Im new to this.  Also what about the "input_vendor_id" and "input_product_id"?

In the case of the 8BitDo Arcade Stick  (Model 80FE) it has firmware that can be upgraded, should I add that info as well even thought it is not in those config lists? I looked at a 8BitDo SN30 USB (8Bitdo_SF30_USB.cfg) as an example for me to start.

**Comment by hizzlekizzle** [comment]
You can create most of the profile directly in RetroArch in settings > input > port 1 controls. Just return all inputs to default, map everything, then 'save controller profile'. It'll have the basic button assignments in there, but you will need to add any other metadata (like the firmware info and button labels) via text editor (notepad++ is a good one).

**Comment by Rstation4** [comment]
I've tried to test this out on RetroArch 1.9.1 and on a Lakka OS nightly build but im not getting results. On Retroarch it gets a error, on Lakka OS it says successful but I dont see where the config is saved to.

Why are these labeled as Xbox 360 controllers as well?

RA 1.9.1
![RA Linux input](https://user-images.githubusercontent.com/73009731/118761393-2c387700-b829-11eb-91bf-9a43bec2fef2.png)

Lakka OS Nightly Build 
![Lakka OS controller input](https://user-images.githubusercontent.com/73009731/118761427-38243900-b829-11eb-9955-b5d50139cc8c.png)

**Comment by hizzlekizzle** [comment]
If it reports as an xbox 360 controller, that means you're using one of the pairing modes that lies about their vid/pid for compatibility purposes. Usually, the "android" pairing mode will give you the real ones.

**Comment by offalynne** [comment]
I don't believe this model actually has a unique pairing mode. It's either S (Switch) or X (XInput).

**Comment by Rstation4** [comment]
They emailed me this response but these guys don't specify which controllers use these inputs. 
"_Hola.

There are differences between products.

Each mode of the controller:

Y+START = Switch MODE
A+START = macOS MODE
B+START = D-Input MODE
X+START = X-Input MODE

*Ensure the controller is turn-off.

X+START to turn-on the controller.
Hold PAIR 3sec to enter pairing mode.

Go to Pi device's Bluetooth setting --> pair with controller.

Kind regards._"

These input instructions are not included in the manual for the SN30 Pro. Unless they made a mistake and gave me instuctions for the SN30 Pro + which has Bluetooth capabilities. The Arcade Stick on the other hand you can update the firmware. It acts a bit weird with both RetroPie and Lakka OS, Sometimes LS (Left Stick Mode) does not input everything and it I end up switching the dial to DS (Dip Stick Mode).  

Where can I find the auto config file that is saved from the port 1 input?

**Comment by Rstation4** [comment]
I notice that both the 8bitDo Arcade Stick Model 80FE and the 8bitDo SN30 Pro Wired controller both have the same Vendor id and input product id as the Xbox 360 gamepad. Is there other gamepads that do this?
input_vendor_id = "1118"
input_product_id = "654"

This may have been intentional by 8bitDo for compatibility.

**Comment by offalynne** [comment]
Yes

**Comment by RobLoach** [comment]
I think this was added already? Mind re-opening if it wasn't added in? I see a few 8bit do arcade stick conigs.

**Comment by RobLoach** [comment]
I think this was added already? Mind re-opening if it wasn't added in? I see a few 8bit do arcade stick conigs.
