### ISSUE TITLE
Amazon Fire TV Remote.cfg has been messed up.

### ISSUE THREAD

**Issue by robwill80** [libretro/retroarch-joypad-autoconfig#777]
Hi. There's an issue with the file at Android/Amazon Fire TV Remote.cfg. Someone edited it with the intention of swapping the OK and Back buttons, but didn't account for the option for it in Settings > Input > Menu Controls. The user then continued to experiment with the file, making the remote's actual layout senseless for menu navigation.

What's more, the user did not change the input descriptors to match the new inputs, so some of the options now have incorrect values in the RetroArch input menu.

I'd like to ask that this file be reverted back to the condition it was in before changes were made approximately two weeks ago, fixing 3 input errors. Namely,

- `input_a_btn = "82"` reverted back to `"23"` - "23" is the Center button on the remote.
- `input_b_btn = "23"` reverted back to `"4"` - "4" is the Back button on the remote.
- `input_start_btn = "4"` reverted back to `"82"` - "82" is the Menu button on the remote.

Thanks,

**Comment by markwkidd** [comment]
@farmerbb do I understand correctly that you are one of the maintainers of the Amazon version of the app? Is this in your wheelhouse?

**Comment by farmerbb** [comment]
I contribute to the general Android portions of the codebase, not to the Fire TV-specific stuff.  @fpscan do you mind looking at this?

**Comment by fpscan** [comment]
Yeah, it's needed to be like that, we had a talk with Amazon representative and explained why controller layout is like that but   they didn't liked the way center button and back button. So we offered Wii remote type layout, I explained the layout and they also didn't liked that, they wanted Center button enter. We had to make this change...

**Comment by robwill80** [comment]
Okay, you didn't say exactly how Amazon wanted those controls to be, so I'll take a guess. I assume that they want the Center button to operate as "OK," and the Back button to operate as "Back," right? If so, that's perfect... why was the config file changed?

To be clear, the Center button _was_ "OK." The Back button _was_ "Back." This is assuming the "Menu Swap OK and Cancel Buttons" option is turned "Off," and standard gamepads follow the Super NES layout (A on the right, B on the bottom, etc - which the port control options reference explicitly). It also follows the Wiimote example, as the A Button is the biggest button in the centre of the Wiimote, and the Start button equivalent is in the same position on Wiimote and Fire TV Remote. This is an ideal solution, on all fronts.

Right now, for RetroArch menu navigation, the Menu button is "OK," the Center button is "Back," and the Back button does nothing... that is unintuitive to say the least, And that's also not mentioning that those same controls are currently identified incorrectly in the options menu.

Amazon agreed to that?

**Comment by fpscan** [comment]
So I just checked and yeah, Center button work as enter and back button doesn't work as it's intended to be but I don't understand your proposition. 

Do you mean that we should have separate Android build which has "Menu Swap OK and Cancel Buttons" already on just for Amazon Appstore? What I'm going to do now is just changing between FireTV remote menu button and back button.

**Comment by robwill80** [comment]
The Center button works as enter for you? Ah, I see. If that "Menu Swap" option is turned "On" by default, then that's my mistake, and I apologise. No, I'm not suggesting separate builds for Amazon or Google.

I have been using a sideloaded RetroArch on Fire TV for quite a few years now, so I just assumed that option's default "favoured" a Nintendo layout over Xbox, since (like I said) the port control options do refer to the ABXY Buttons in a Super NES layout.

Switching the Menu and Back button input on the Remote would be great, and I will turn on "Menu Swap" on my end. Thank you.

**Comment by fpscan** [comment]
So here is how it will be.
![REMOTE](https://user-images.githubusercontent.com/4651944/126714130-7d4d28ee-ffc6-4ccc-bee8-3daebd48c145.jpeg)

**Comment by robwill80** [comment]
Hold on - that's the layout I asked for earlier (reverting the changes made to the file). I thought you wanted the Centre button to be "B," and the Back button to be "A" (i.e. "Menu Swapped")

Sorry, I'm not trying to mess you around. I just want this thing fixed, like you do.

**Comment by fpscan** [comment]
Okay, I just didn't focused the labels but I changed them now.

**Comment by Xulomali** [comment]
Encontré que la tecla central corresponde a la tecla 66.

si quieres directamente en el retroarch.cfg,
normalmente se ubica en: 

`/Android/data/com.retroarch.ra32/files/retroarch.cfg`

los que haya, cámbialos por :
```
input_player1_a_btn = "66"       # ENTER → confirmar/OK (botón central)
input_player1_b_btn = "4"        # BACK → cancelar/volver
input_player1_start_btn = "82"   # MENU
menu_swap_ok_cancel_buttons = "false"
```

ya después lo demás lo configuras ya con el mando, recuerda en cada instalación nueva modificar ese archivo, si no te será inútil el mando
