### ISSUE TITLE
Possible to use VID/PID/SERIAL?

### ISSUE THREAD

**Issue by sonik-br** [libretro/retroarch-joypad-autoconfig#791]
It's common to have controllers with the same generic VID and PID as the xbox 360 controller.
Would be possible to match the product serial too?
I't would be handy for DIY arduino adapters too as all of them uses the same VID and PID.
I got the idea from the Mister Fpga project as it uses the serial to identify unique adapters.

**Comment by offalynne** [comment]
currently only vid pid and device name. i agree adding a field for bcdDevice would be ideal.

**Comment by sonik-br** [comment]
I do have a bunch of arduino adapters that could benefit from this.
It's a planned feature? I could not find any info on this.

**Comment by hizzlekizzle** [comment]
No plan for it right now, but it would be good, yes.

**Comment by sonik-br** [comment]
Thanks. I will keep an eye on it.
