### ISSUE TITLE
Retroarch Bind All... seems to not register all the possible analog axes

### ISSUE THREAD

**Issue by rsn8887** [libretro/retroarch-joypad-autoconfig#80]
I compared retroarch bind all functionality with the controller diagnostic debug function in Mupen 64 AE. 

By default, without a special .kl file, Android seems to map quite a few analog axes from the USB controller to android standard axes names, prefixed with an Axis_ (not shown here): 
X,Y,Z,Rx,Ry,Rz,Throttle,Rudder,Wheel,Gas,Brake, Hat_X, Hat_Y (see the bottom of generic.kl here: https://android.googlesource.com/platform/frameworks/base/+/cd92588/data/keyboards/Generic.kl)

I could see all the above axes in Mupen64 AE, but some of them do not register in Retroarch Bind All.

I suspect retroarch is only "listening" for a subset of the available analog axes, and might need to be fixed to look for all of them. I suspect the subset is X,Y,Z,Rz,LTrigger,RTrigger, and maybe a few others. But it looks like Rx,Ry and maybe more do not register.

Sidenote: Sadly, the LTrigger and RTrigger analog L/R controls are NOT mapped by Android in the generic.kl file, which is annoying to say the least. Instead, "Gas" and "Brake" are mapped. To get analog LTrigger and RTrigger functionality, it looks like one has to resort to Gas and Brake which probably no game supports, or make a custom .kl keylayout file to remap those.

**Comment by RobLoach** [comment]
Been a bunch of updates in the menu system in RA. More than 5 years since this was opened. Going to close for now. Thanks!
