### ISSUE TITLE
Multiple controllers with 121/17 VID/PID

### ISSUE THREAD

**Issue by josephdouce** [libretro/retroarch-joypad-autoconfig#815]
udev/Retrolink_Sega_Saturn_USB_GamePad.cfg
udev/Hyperkin_Genesis_6_Button.cfg
udev/retro-bit SEGA Genesis 6-Button.cfg
udev/YSTEK MICREAL USB Gamepad.cfg
udev/SWITCH CO.,LTD. USB Gamepad .cfg

All the above controllers are on 121/17 and it seems like it's a lottery which is used, seems I may be on a slightly older version as SWITCH CO is now commented but I keep getting a random selection of sega 6-Button, Sega 8-Button, SWITCH CO

**Comment by offalynne** [comment]
yep, same problem as 121/6 to a lesser extent. vid/pid should be commented out so the configs can match on name, or failing that user configuration.

**Comment by josephdouce** [comment]
Just leave the most popular in, and then user config to override on all others. If there's os only 1 at least its consistent, having 5 with uncommented pid/vid means I have to user override all of those configs.

**Comment by offalynne** [comment]
I don’t think you understand how this works. Without VID and PID active the config matches on name. The goal of autoconfig is to select the best from available options, not provide one (more than likely wrong) option.

**Comment by josephdouce** [comment]
D


Kind Regards

Joseph Douce BEng (Hons) MIET

**Comment by RobLoach** [comment]
I've updated some of the configs across those VIDs. Thanks for the debugging. Mind having another look? We could likely do a bit more tweaking on it.

**Comment by josephdouce** [comment]
Sure thing.

Kind Regards

Joseph Douce BEng (Hons) MIET

**Comment by RobLoach** [comment]
CLosing this one. Let me know if you're still running into troubles.
