### ISSUE TITLE
[Pull requests] Add Dual Sense PS5 controller support

### ISSUE THREAD

**Issue by SoloBackup** [libretro/retroarch-joypad-autoconfig#817]
Hello, i hope that in the near future, the project will have improved support for PS5 controllers.

In the version that i use (RetroArch 1.9.14, Windows 11) Dualsense works perfectly, except the rumble of controller.
When connecting the Dualsense it is recognized as Dualshock 4 Controller or Wireless Controller, so i think that's the problem with rumble not working. Dualsense has a different rumble scheme than Dualshock 4, and therefore rumble does not work with most emulators from previous consoles (tested both on RetroArch and as on stand-alone Dolphin, PCSX2 and others and the rumble don't work too). The only one that worked rumble was the yuzu.
If the implementation is possible in the future, I would be very happy and pleased.
Anyway, congratulations on the project and thanks for providing us with this amazing emulation tool.

**Comment by RobLoach** [comment]
Moved this over to retroarch-joypad-autoconfig... Would you mind setting your controller up, and then exporting the config profile and uploading the file here? RetroArch reads the profiles from this autoconfig repository, so the more profiles we have with device IDs the better... While the rumble may or may not work, having it recognized correctly is a good first step.

**Comment by SoloBackup** [comment]
OK thank you. I checked here and indeed it was in autoconfiguration. So i did the complete configuration manually and here is the generated file all configured in input 1.
OBS1: I tested the USB and Bluetooth and saw that the result is absolutely the same (it is recognized as "Dualshock 4 Controller" and the buttons are named exactly the same, so much so that when saving in the bluetooth attempt there was no change in the file because both entries are recognized equally, so i will only upload one file.)
NOTE 2: I set the position of the buttons fully corresponding with the inputs shown without any changes. Except for the extra buttons that are: A click on Touchpad button, the PlayStation Button and the Microphone Button. I kept them in the last options as shown in this image because i didn't know where to keep them.
Thank you very much and i hope this helps.
![EXTRA BUTTONS](https://user-images.githubusercontent.com/84431888/149685426-72463ffe-2589-4f1e-8296-8f4ff00ee262.jpg)
[retroarch config file.zip](https://github.com/libretro/retroarch-joypad-autoconfig/files/7878358/retroarch.config.file.zip)

**Comment by Saberwolf64** [comment]
here is my config profile for Dual Sense 5 controller For Android this config works both with OTG cable and BT

MIC Mute button is 107 
TouchPad Click 106 
PS button is 110
FYI
```
input_driver = "android"
input_device = "Wireless Controller"
input_device_display_name = "DualSense 5"
input_vendor_id = "1356"
input_product_id = "3302"


input_b_btn = "97"
input_y_btn = "96"
input_select_btn = "104"
input_start_btn = "105"
input_up_btn = "h0up"
input_down_btn = "h0down"
input_left_btn = "h0left"
input_right_btn = "h0right"
input_a_btn = "98"
input_x_btn = "99"
input_l_btn = "100"
input_r_btn = "101"
input_l2_btn = "102"
input_r2_btn = "103"
input_l3_btn = "109"
input_r3_btn = "108"
input_l_x_plus_axis = "+0"
input_l_x_minus_axis = "-0"
input_l_y_plus_axis = "+1"
input_l_y_minus_axis = "-1"
input_r_x_plus_axis = "+2"
input_r_x_minus_axis = "-2"
input_r_y_plus_axis = "+3"
input_r_y_minus_axis = "-3"
input_menu_toggle_btn = "110"


input_b_btn_label = "Cross"
input_y_btn_label = "Square"
input_select_btn_label = "Create"
input_start_btn_label = "Options"
input_up_btn_label = "D-Pad Up"
input_down_btn_label = "D-Pad Down"
input_left_btn_label = "D-Pad Left"
input_right_btn_label = "D-Pad Right"
input_a_btn_label = "Circle"
input_x_btn_label = "Triangle"
input_l_btn_label = "L1"
input_r_btn_label = "R1"
input_l2_btn_label = "L2"
input_r2_btn_label = "R2"
input_l3_btn_label = "L3"
input_r3_btn_label = "R3"
input_l_x_plus_axis_label = "Left Analog X+"
input_l_x_minus_axis_label = "Left Analog X-"
input_l_y_plus_axis_label = "Left Analog Y+"
input_l_y_minus_axis_label = "Left Analog Y-"
input_r_x_plus_axis_label = "Right Analog X+"
input_r_x_minus_axis_label = "Right Analog X-"
input_r_y_plus_axis_label = "Right Analog Y+"
input_r_y_minus_axis_label = "Right Analog Y-"
input_menu_toggle_btn_label = "PS"
```

**Comment by Saberwolf64** [comment]
@solobackup this is should be closed support has been added to autoconfig in the udev android and dinput

**Comment by RobLoach** [comment]
Thanks for the help all!

**Comment by RudyBzhBzh** [comment]
Hi, sorry if my post should not be there but these associations are not correct for me.

Here is what I have with my two Dual Sense 5 connected (wireless or wired) to an Nvidia Shield Pro :
```
input_player1_b_btn = "96"
input_player1_y_btn = "99"
input_player1_select_btn = "4"
input_player1_start_btn = "108"
input_player1_a_btn = "97"
input_player1_x_btn = "100"
input_player1_l_btn = "102"
input_player1_r_btn = "103"
input_player1_l2_btn = "104"
input_player1_r2_btn = "105"
input_player1_l3_btn = "106"
input_player1_r3_btn = "107"
```
Other values are correct for me (I'm just not sure for "PS Button", because, for me, it quits retroarch so I can't get it's value)

If I manually set the above values in retroarch.cfg for player1 and player2 :
- I can play games correctly with my 2 remotes.
- I can navigate in retroarch menu with 1st remote : "B button" to validate and "A button" to go back.

BUT I can't use the 2nd remote in retroarch menu because "A button" is to validate and "B button" is like not affected.

Strangely, the native Shield Pro remote (not the controller) seems to but misaffected also : the "back button" is to validate (like "B button") and the "Select button" is to go back (like "A button"). 

I'm really lost about this... any idea of what it could be ?

Thanks a lot.

**Comment by Saberwolf64** [comment]
what driver are you using for Shield input it could be different make shure your are either useing Dinput or android i have tested the settings in windows and on a android tablet double check your driver for input and submit bug report for it 

it is vary important that you have this first at the top of your config

input_driver = "android" Or dinput 
input_device = "Wireless Controller"
input_device_display_name = "DualSense 5"
input_vendor_id = "1356"
input_product_id = "3302"

what might behapping is you might be using udev just double check your driver you are using in RA
