### ISSUE TITLE
“Gamesir-T4 1.25” joypad can'not  support

### ISSUE THREAD

**Issue by hmony** [libretro/retroarch-joypad-autoconfig#865]
I: Bus=0003 Vendor=05ac Product=061c Version=0111
N: Name="   Gamesir-T4 1.25"
P: Phys=usb-xhci-hcd.0.auto-1.1/input0
S: Sysfs=/devices/platform/ff500000.dwc3/xhci-hcd.0.auto/usb1/1-1/1-1.1/1-1.1:1.0/0003:05AC:061C.0006/input/input10
U: Uniq=
H: Handlers=mouse0 event3 js0 
B: PROP=0
B: EV=1f
B: KEY=4000 0 7fff000000070000 0 0 0 0
B: REL=3
B: ABS=30627
B: MSC=10
[Gamesir-T4 1.25.zip](https://github.com/libretro/retroarch-joypad-autoconfig/files/9732808/Gamesir-T4.1.25.zip)

**Comment by RobLoach** [comment]
Could you upload the .cfg using markdown? It's ` ` ` in a row to make code blocks.
