### ISSUE TITLE
Mayflash Arcade Fightstick F500 collides with SPEEDLINK COMPETITION PRO Game Controller for Android

### ISSUE THREAD

**Issue by thingsiplay** [libretro/retroarch-joypad-autoconfig#884]
I first created an issue in RetroArch: https://github.com/libretro/RetroArch/issues/14867

My suggestion is to copy the existing "autoconfig/udev/Mayflash_Arcade_Fightstick_F300_CONSOLE.cfg", which is used for two versions of the same stick (F300 and F500) and rename device and display name in the config. Because without this custom config RetroArch will always pick the wrong "autoconfig/udev/SPEEDLINK COMPETITION PRO Game Controller for Android.cfg" for some reason. My suggestion is:

_Mayflash_Arcade_Fightstick_F500_CONSOLE.cfg_:

```
input_driver = "udev"
input_device = ". MAYFLASH Arcade Fightstick F500"
input_device_display_name = "MAYFLASH Arcade Fightstick F500 (CONSOLE)"
input_vendor_id = "121"
input_product_id = "6172"

input_select_btn = "10"
input_start_btn = "11"
input_menu_toggle_btn = "12"
#
input_up_btn = "h0up"
input_down_btn = "h0down"
input_left_btn = "h0left"
input_right_btn = "h0right"
#
input_y_btn = "3"
input_x_btn = "4"
input_b_btn = "0"
input_a_btn = "1"
#
input_l_btn = "6"
input_r_btn = "7"
input_l2_btn = "8"
input_r2_btn = "9"
#
input_l_x_plus_axis = "+0"
input_l_x_minus_axis = "-0"
input_l_y_plus_axis = "-1"
input_l_y_minus_axis = "+1"
input_r_x_plus_axis = "+2"
input_r_x_minus_axis = "-2"
input_r_y_plus_axis = "-3"
input_r_y_minus_axis = "+3"
```

**Comment by gouchi** [comment]
@thingsiplay It seems that [SPEEDLINK COMPETITION PRO Game Controller for Android .cfg](https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/SPEEDLINK%20COMPETITION%20PRO%20Game%20Controller%20for%20Android%20.cfg) has already been updated to avoid conflict with [Mayflash_Arcade_Fightstick_F300_CONSOLE.cfg](https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/Mayflash_Arcade_Fightstick_F300_CONSOLE.cfg) via this [commit](https://github.com/libretro/retroarch-joypad-autoconfig/commit/b84f7b77f3c580568387d54dbb9dbc421b8cf8c8).

if I understand correctly, we should have something ?

Mayflash_Arcade_Fightstick_F500_CONSOLE.cfg:

```
input_driver = "udev"
input_device = ". MAYFLASH Arcade Fightstick F500"
input_device_display_name = "MAYFLASH Arcade Fightstick F500 (CONSOLE)"
input_vendor_id = "121"
input_product_id = "6172"

input_select_btn = "10"
input_start_btn = "11"
input_menu_toggle_btn = "12"
#
input_up_btn = "h0up"
input_down_btn = "h0down"
input_left_btn = "h0left"
input_right_btn = "h0right"
#
input_y_btn = "3"
input_x_btn = "4"
input_b_btn = "0"
input_a_btn = "1"
#
input_l_btn = "6"
input_r_btn = "7"
input_l2_btn = "8"
input_r2_btn = "9"
#
input_l_x_plus_axis = "+0"
input_l_x_minus_axis = "-0"
input_l_y_plus_axis = "-1"
input_l_y_minus_axis = "+1"
input_r_x_plus_axis = "+2"
input_r_x_minus_axis = "-2"
input_r_y_plus_axis = "-3"
input_r_y_minus_axis = "+3"
```

Mayflash_Arcade_Fightstick_F300_CONSOLE.cfg

```
input_driver = "udev"
input_device = "MAYFLASH Arcade Fightstick F300"
input_device_display_name = "MAYFLASH Arcade Fightstick F300 (CONSOLE)"
input_vendor_id = "121"
input_product_id = "6172"
#
input_select_btn = "10"
input_start_btn = "11"
input_menu_toggle_btn = "12"
#
input_up_btn = "h0up"
input_down_btn = "h0down"
input_left_btn = "h0left"
input_right_btn = "h0right"
#
input_y_btn = "3"
input_x_btn = "4"
input_b_btn = "0"
input_a_btn = "1"
#
input_l_btn = "6"
input_r_btn = "7"
input_l2_btn = "8"
input_r2_btn = "9"
#
input_l_x_plus_axis = "+0"
input_l_x_minus_axis = "-0"
input_l_y_plus_axis = "-1"
input_l_y_minus_axis = "+1"
input_r_x_plus_axis = "+2"
input_r_x_minus_axis = "-2"
input_r_y_plus_axis = "-3"
input_r_y_minus_axis = "+3"
```
SPEEDLINK COMPETITION PRO Game Controller for Android .cfg

```
input_driver = "udev"
input_device = "SPEEDLINK COMPETITION PRO Game Controller for Android "
input_device_display_name = "Speedlink Competition Pro Extra SL-650212-BKRD"
input_vendor_id = "121"
input_product_id = "6172"
input_b_btn = "3"
input_b_btn_label = "Left Round"
input_a_btn = "0"
input_a_btn_label = "Right Round"
input_select_btn = "4"
input_select_btn_label = "Left Triangle"
input_start_btn = "1"
input_start_btn_label = "Right Triangle"
input_up_axis = "-1"
input_up_axis_label = "Up"
input_down_axis = "+1"
input_down_axis_label = "Down"
input_left_axis = "-0"
input_left_axis_label = "Left"
input_right_axis = "+0"
input_right_axis_label = "Right"
```

**Comment by thingsiplay** [comment]
I no longer use the Myflash Arcade Stick, so cannot test it immediately (still have it, just unplugged). Good to know they updated it with a "workaround". They just out-commented the ids, which are the same for these Speedlink and Myflash device. So maybe you don't need to add any custom config. Out-commenting has the same effect as deleting the lines:

```
#input_vendor_id = "121"
#input_product_id = "6172"
```

So if you put them back to SPEEDLINK COMPETITION PRO Game Controller for Android .cfg, then it will have higher priority over Mayflash. I don't know which of those devices you want to use. If you have trouble, just put a hash symbol in front of those lines like above. That means RetroArch ignores those lines and the id is no longer in conflict.

**Comment by gouchi** [comment]
@thingsiplay Thank you for the feedback. I don't have these controllers to make some test.

If the workaround is ok for you, please close this issue.

Thank you.
