### ISSUE TITLE
[Feature request] Sony DualSense Edge support

### ISSUE THREAD

**Issue by davidhedlund** [libretro/retroarch-joypad-autoconfig#900]
It would be nice with the addition of a [PlayStation 5 DualSense Edge](https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/Sony_PlayStation5_DualSense_Edge.cfg)

**Comment by offalynne** [comment]
this project is the product of user submission. if you want this change, buy the controller, make the mappings, and contribute them.

**Comment by davidhedlund** [comment]
> this project is the product of user submission. if you want this change, buy the controller, make the mappings, and contribute them.

I've filed feature request for controllers in other repos and there was never a problem. However, I've already spent €200 on two controllers, my wallet is too small for the DualSense Edge that has a price tag of €240.

**Comment by offalynne** [comment]
That's fine, my point is there are hundreds if not thousands of unique controller devices, and we may like to have mappings for all of them, in every configuration, on every OS: making issues is not a productive way to help solve this problem

**Comment by davidhedlund** [comment]
Solved:
* https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/Sony%20Interactive%20Entertainment%20DualSense%20Edge%20Wireless%20Controller.cfg
