### ISSUE TITLE
Automatically select controller based on Linux version compatibility

### ISSUE THREAD

**Issue by davidhedlund** [libretro/retroarch-joypad-autoconfig#901]
Merged to:
* https://github.com/libretro/RetroArch/issues/15994

**Comment by davidhedlund** [comment]
@hizzlekizzle What do you think about it?

**Comment by hizzlekizzle** [comment]
This seems like useful information for the profile, and I'm not against having pretty much anything as a comment, or even not a comment as long as it gets ignored by RetroArch unless/until we add the functionality to parse and act on it.

**Comment by davidhedlund** [comment]
> This seems like useful information for the profile, and I'm not against having pretty much anything as a comment, or even not a comment as long as it gets ignored by RetroArch unless/until we add the functionality to parse and act on it.

Thank you. I have added Linux compatibility references to the .cfg files. Can you accept my pull requests?

**Comment by hizzlekizzle** [comment]
I can't, but I'll mention it to someone who can.

**Comment by offalynne** [comment]
assuming you mean "kernel version" this would indeed be useful so older versions of otherwise colliding mappings can be differentiated as native drivers develop. once again this is an issue for the RetroArch frontend project (which generates and selects these files), not the auotoconfig repo, which only contains them.

**Comment by davidhedlund** [comment]
> assuming you mean "kernel version" this would indeed be useful so older versions of otherwise colliding mappings can be differentiated as native drivers develop. once again this is an issue for the RetroArch frontend project (which generates and selects these files), not the auotoconfig repo, which only contains them.

Merged (see top post). Thanks.
