### ISSUE TITLE
Suggestion: Use the original hexadecimal instead of converted decimal values

### ISSUE THREAD

**Issue by davidhedlund** [libretro/retroarch-joypad-autoconfig#904]
Example, in [Sony Interactive Entertainment Wireless Controller.cfg](https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/Sony%20Interactive%20Entertainment%20Wireless%20Controller.cfg)

```
input_vendor_id = "1356"
input_product_id = "3302"
```

Demonstrate that the above values are converted from hexadecimal to decimal:
```
$ lsusb
Bus 003 Device 002: ID 054c:0ce6 Sony Corp. Wireless Controller
$ echo $((0x054c))
1356
$ echo $((0x0ce6))
3302
```

However, the hexadecimal values are officially the vendor ID/product ID as demonstrated by `lsusb` above, so the decimal numbers cannot be check in databases (example: http://www.linux-usb.org/usb.ids). Therefore it could be more beneficial to use the original decimal values.

What is the main reason why decimal values are used?

**Comment by offalynne** [comment]
this repo is for autoconfig data. you're making a lot of issues/noise about longstanding decisions made in the retroarch project itself. while the changes you want (assuming they are by consensus desirable) may impact autoconfig data if they are made, you need to take those issues to the retroarch project itself, not this repo.
