### ISSUE TITLE
Google Stadia Controller button #8

### ISSUE THREAD

**Issue by theflyingape** [libretro/retroarch-joypad-autoconfig#919]
Any chance `udev/Google LLC Stadia Controller rev. A.cfg` can have its **Stadia** button configured for RetroArch Menu toggle like the PlayStation controller?
```
input_menu_toggle_btn = "8"
input_menu_toggle_btn_label = "Stadia"
```

**Comment by cmitu** [comment]
Solved by https://github.com/libretro/retroarch-joypad-autoconfig/pull/1113
