### ISSUE TITLE
8BitDo Micro - not configured

### ISSUE THREAD

**Issue by xXkr13g3rXx** [libretro/retroarch-joypad-autoconfig#927]
Hello! A question: Is the 8BitDo Micro supported? I get it to run in Retropie and their menu for example, but inside games or the config menus it doesn't work. Get in games initially in the bottom left the pop-up: not configured.

**Comment by hizzlekizzle** [comment]
That means it's recognized but--you guessed it--not configured, which means we don't have an autoconfig profile for it yet.

You could make an autoconfig profile for it and submit it, if you would like it to be included in the future.

**Comment by xXkr13g3rXx** [comment]
Thanks for the quick info. Do you have any tutorial for this?

**Comment by xXkr13g3rXx** [comment]
https://www.retroarch.com/index.php?page=controller-autoconfig

I think this one will work
