### ISSUE TITLE
Include directory name and .cfg file name in the controller notification message

### ISSUE THREAD

**Issue by davidhedlund** [libretro/retroarch-joypad-autoconfig#946]
Merged to:
* https://github.com/libretro/RetroArch/issues/15993

**Comment by offalynne** [comment]
This is not the RetroArch frontend repository. This is: https://github.com/libretro/RetroArch

**Comment by davidhedlund** [comment]
> This is not the RetroArch frontend repository. This is: https://github.com/libretro/RetroArch

Merged (see top post). Thanks.
