### ISSUE TITLE
[feature request]: Load Configurations: Settings -> Input -> Port [1-5] Controls

### ISSUE THREAD

**Issue by davidhedlund** [libretro/retroarch-joypad-autoconfig#949]
Merged to:
* https://github.com/libretro/RetroArch/issues/15992

**Comment by offalynne** [comment]
This is not the RetroArch frontend repository. This is:  https://github.com/libretro/RetroArch

**Comment by davidhedlund** [comment]
> This is not the RetroArch frontend repository. This is: https://github.com/libretro/RetroArch

Merged (see top post). Thanks.
